import {SafeAreaView} from "react-native-safe-area-context";
import {useEffect,useRef,useState} from 'react';
import {Keyboard,KeyboardAvoidingView,Modal,Platform,Pressable,ScrollView,StyleSheet,View} from 'react-native';
import DateTimePicker from '@react-native-community/datetimepicker';
import type {HouseholdCostFrequency,HouseholdCostCategory} from '@eavesence/core/householdCosts';
import {DisclosureIcon} from './BrandMotion';
import {revealInput} from './ScrollNavigation';
import {FormInput,KeyboardScrollContext} from './FormInput';
import {FormSection,FormSubmitButton,useFormAction} from './FormSection';
import {LocalizedText as Text,useMobileLocale} from './i18n';
type Props={name:string;amount:string;frequency:HouseholdCostFrequency;date:string;deadline:string;category:HouseholdCostCategory;editing:boolean;onName:(v:string)=>void;onAmount:(v:string)=>void;onFrequency:(v:HouseholdCostFrequency)=>void;onDate:(v:string)=>void;onDeadline:(v:string)=>void;onCategory:(v:HouseholdCostCategory)=>void;onSave:()=>Promise<unknown>;onClose:()=>void};
const intervals:HouseholdCostFrequency[]=['weekly','monthly','quarterly','half-yearly','yearly'];
const cats:HouseholdCostCategory[]=['housing','energy','insurance','subscriptions','mobility','financing','leisure','other'];
function Close({onClose}:{onClose:()=>void}){const action=useFormAction(),de=useMobileLocale()==='de';return <Pressable accessibilityRole="button" accessibilityLabel={de?'Abbrechen':'Cancel'} disabled={action?.busy} onPress={()=>{Keyboard.dismiss();onClose();}} style={s.back}><Text style={s.arrow}>‹</Text></Pressable>;}
export function CostEditor(p:Props){
 const de=useMobileLocale()==='de',t=(a:string,b:string)=>de?a:b;
 const [more,setMore]=useState(false),[choice,setChoice]=useState<'frequency'|'category'|null>(null),[dateField,setDateField]=useState<'date'|'deadline'|null>(null),[draftDate,setDraftDate]=useState(new Date());
 const scroll=useRef<ScrollView>(null);
 const [keyboardVisible,setKeyboardVisible]=useState(false);
 useEffect(()=>{const show=Keyboard.addListener("keyboardDidShow",()=>setKeyboardVisible(true)),hide=Keyboard.addListener("keyboardDidHide",()=>setKeyboardVisible(false));return()=>{show.remove();hide.remove();};},[]);
 const cadence=(v:HouseholdCostFrequency)=>(de?{weekly:'Wöchentlich',monthly:'Monatlich',quarterly:'Alle 3 Monate','half-yearly':'Alle 6 Monate',yearly:'Jährlich'}:{weekly:'Weekly',monthly:'Monthly',quarterly:'Every 3 months','half-yearly':'Every 6 months',yearly:'Yearly'})[v];
 const category=(v:HouseholdCostCategory)=>(de?{housing:'Wohnen',energy:'Energie',insurance:'Versicherung',subscriptions:'Verträge & Abos',mobility:'Mobilität',financing:'Finanzierung',leisure:'Freizeit',other:'Sonstiges'}:{housing:'Housing',energy:'Energy',insurance:'Insurance',subscriptions:'Contracts & subscriptions',mobility:'Transport',financing:'Financing',leisure:'Leisure',other:'Other'})[v];
 const parseDate=(v:string)=>{const [d,m,y]=v.split('.').map(Number);const parsed=new Date(y,m-1,d,12);return Number.isFinite(parsed.getTime())?parsed:new Date();};
 const formatDate=(d:Date)=>`${String(d.getDate()).padStart(2,'0')}.${String(d.getMonth()+1).padStart(2,'0')}.${d.getFullYear()}`;
 const labelDate=(v:string)=>v?new Intl.DateTimeFormat(de?'de-AT':'en-GB',{day:'numeric',month:'long',year:'numeric'}).format(parseDate(v)):t('Datum auswählen','Choose a date');
 function openDate(field:'date'|'deadline'){Keyboard.dismiss();setDraftDate(parseDate(field==='date'?p.date:p.deadline));setDateField(field);}
 function applyDate(d:Date){if(dateField==='date')p.onDate(formatDate(d));else p.onDeadline(formatDate(d));}
 function selectRow(label:string,value:string,action:()=>void){return <Pressable accessibilityRole="button" accessibilityLabel={`${label}: ${value}`} onPress={()=>{Keyboard.dismiss();action();}} style={s.select}><View style={s.flex}><Text style={s.label}>{label}</Text><Text style={s.selected}>{value}</Text></View><Text style={s.chevron}>›</Text></Pressable>;}
 return <Modal visible animationType="slide" onRequestClose={p.onClose}><SafeAreaView style={s.safe}><KeyboardAvoidingView behavior={Platform.OS==='ios'?'padding':undefined} style={s.safe}><FormSection style={s.safe} onSave={p.onSave} saveLabel={t('Kosten speichern','Save cost')}>
  <View style={s.header}><Close onClose={p.onClose}/><Text accessibilityRole="header" style={s.title}>{p.editing?t('Kosten bearbeiten','Edit cost'):t('Kosten hinzufügen','Add cost')}</Text><View style={s.back}/></View>
  <KeyboardScrollContext.Provider value={input=>revealInput(scroll.current,input)}><ScrollView ref={scroll} keyboardShouldPersistTaps="handled" keyboardDismissMode="interactive" contentContainerStyle={s.body}>
   <View style={s.group}><View style={s.input}><FormInput label={t('Name','Name')} value={p.name} onChangeText={p.onName} placeholder={t('z. B. Internet','e.g. Internet')} style={s.inputStyle}/></View><View style={s.input}><FormInput label={t('Betrag','Amount')} value={p.amount} onChangeText={p.onAmount} keyboardType="decimal-pad" placeholder="0,00" style={s.inputStyle}/></View>
    {selectRow(t('Wie oft?','How often?'),cadence(p.frequency),()=>setChoice('frequency'))}
    {selectRow(t('Nächste Zahlung (optional)','Next payment (optional)'),labelDate(p.date),()=>openDate('date'))}
    <Pressable accessibilityRole="button" accessibilityState={{expanded:more}} onPress={()=>setMore(!more)} style={s.select}><Text style={s.selected}>{t('Zusatzangaben','More details')}</Text><DisclosureIcon open={more}/></Pressable>
    {more&&<>{selectRow(t('Kategorie','Category'),category(p.category),()=>setChoice('category'))}{selectRow(t('Kündigungsfrist (optional)','Cancellation deadline (optional)'),labelDate(p.deadline),()=>openDate('deadline'))}</>}
   </View><Text style={s.note}>{t('Mit einem Datum siehst du, wann die Zahlung ansteht. Du kannst es später ergänzen.','A date shows when this payment is due. You can add it later.')}</Text>
  </ScrollView></KeyboardScrollContext.Provider>
  {!keyboardVisible&&<View style={s.footer}><FormSubmitButton label={t('Kosten speichern','Save cost')} style={s.save} textStyle={s.saveText}/></View>}
 </FormSection></KeyboardAvoidingView></SafeAreaView>
 {choice&&<Modal transparent animationType="fade" onRequestClose={()=>setChoice(null)}><View style={s.overlay}><Pressable accessibilityRole="button" accessibilityLabel={t('Auswahl schließen','Close selection')} style={StyleSheet.absoluteFill} onPress={()=>setChoice(null)}/><View style={s.sheet}><Text style={s.title}>{choice==='frequency'?t('Wie oft?','How often?'):t('Kategorie','Category')}</Text><ScrollView>{(choice==='frequency'?intervals:cats).map(v=><Pressable key={v} accessibilityRole="button" accessibilityState={{selected:choice==='frequency'?v===p.frequency:v===p.category}} onPress={()=>{if(choice==='frequency')p.onFrequency(v as HouseholdCostFrequency);else p.onCategory(v as HouseholdCostCategory);setChoice(null);}} style={s.option}><Text style={s.selected}>{choice==='frequency'?cadence(v as HouseholdCostFrequency):category(v as HouseholdCostCategory)}</Text><Text style={s.selected}>{v===(choice==='frequency'?p.frequency:p.category)?'✓':''}</Text></Pressable>)}</ScrollView><Pressable onPress={()=>setChoice(null)} style={s.option}><Text style={s.note}>{t('Abbrechen','Cancel')}</Text></Pressable></View></View></Modal>}
 {dateField&&<Modal transparent animationType="fade" onRequestClose={()=>setDateField(null)}><View style={s.overlay}><View style={s.sheet}><Text style={s.title}>{dateField==='date'?t('Nächste Zahlung','Next payment'):t('Kündigungsfrist','Cancellation deadline')}</Text>{Platform.OS==='web'?<FormInput label={t('Datum: TT.MM.JJJJ','Date: DD.MM.YYYY')} value={dateField==='date'?p.date:p.deadline} onChangeText={dateField==='date'?p.onDate:p.onDeadline}/>:<DateTimePicker value={draftDate} mode="date" display={Platform.OS==='ios'?'spinner':'default'} locale={de?'de-AT':'en-GB'} onChange={(event,date)=>{if(event.type==='dismissed'){setDateField(null);return;}if(date){setDraftDate(date);if(Platform.OS==='android'){applyDate(date);setDateField(null);}}}}/>}<Pressable accessibilityRole="button" onPress={()=>{if(Platform.OS!=='web')applyDate(draftDate);setDateField(null);}} style={s.save}><Text style={s.saveText}>{t('Datum übernehmen','Use date')}</Text></Pressable><View style={s.dateActions}><Pressable onPress={()=>{if(dateField==='date')p.onDate('');else p.onDeadline('');setDateField(null);}} style={s.option}><Text style={s.note}>{t('Ohne Datum','No date')}</Text></Pressable><Pressable onPress={()=>setDateField(null)} style={s.option}><Text style={s.note}>{t('Abbrechen','Cancel')}</Text></Pressable></View></View></View></Modal>}
 </Modal>;
}
const s=StyleSheet.create({safe:{flex:1,backgroundColor:'#f7f8f4'},header:{flexDirection:'row',alignItems:'center',paddingHorizontal:16,paddingVertical:8,gap:8},back:{width:44,minHeight:44,justifyContent:'center'},arrow:{fontSize:30,color:'#17211f'},title:{fontSize:20,fontWeight:'700',color:'#17211f',flex:1,textAlign:'center'},body:{padding:20,paddingTop:24,gap:16},group:{backgroundColor:'#fff',borderRadius:18,paddingHorizontal:16},input:{paddingVertical:18,borderBottomWidth:1,borderColor:'#e5e9e2'},inputStyle:{borderWidth:0,borderRadius:6,paddingHorizontal:0,minHeight:44,backgroundColor:'#fff'},select:{minHeight:76,paddingVertical:16,borderBottomWidth:1,borderColor:'#e5e9e2',flexDirection:'row',alignItems:'center',justifyContent:'space-between',gap:12},flex:{flex:1,gap:6},label:{fontSize:13,color:'#65716d'},selected:{fontSize:16,fontWeight:'500',color:'#17211f'},chevron:{fontSize:22,color:'#65716d'},note:{fontSize:13,lineHeight:20,color:'#65716d'},footer:{padding:20,paddingTop:12,backgroundColor:'#f7f8f4'},save:{minHeight:52,borderRadius:14,backgroundColor:'#087a45',alignItems:'center',justifyContent:'center',paddingHorizontal:16},saveText:{fontSize:16,fontWeight:'600',color:'#fff'},overlay:{flex:1,backgroundColor:'#0007',justifyContent:'flex-end'},sheet:{backgroundColor:'#f7f8f4',padding:20,paddingBottom:32,borderTopLeftRadius:24,borderTopRightRadius:24,maxHeight:'80%',gap:16},option:{minHeight:52,flexDirection:'row',justifyContent:'space-between',alignItems:'center',borderBottomWidth:1,borderColor:'#e5e9e2'},dateActions:{flexDirection:'row',justifyContent:'space-between'},});
