import {useState} from 'react';
import {Alert,Keyboard,Pressable,StyleSheet,Text,View} from 'react-native';
import {useMemos} from '@eavesence/core/useMemos';
import type {HomeMemo} from '@eavesence/core/memos';
import type {PlanningData} from '@eavesence/core/planning';
import {DisclosureIcon} from './BrandMotion';
import {FormSection,FormSubmitButton} from './FormSection';
import {FormInput} from './FormInput';
import {reconcileMemoReminders} from './reminders';

export function HomeMemos({data,onSave,locale,open,onToggle,initialAdd=false}:{initialAdd?:boolean;data?:PlanningData;onSave:(data:PlanningData)=>void|Promise<void>;open:boolean;onToggle:()=>void;locale:'de'|'en'}) {
  const de=locale==='de',t=(a:string,b:string)=>de?a:b;
  const c=useMemos(data,onSave,de,async(memos,request)=>{
    const status=await reconcileMemoReminders(memos,locale,request);
    return status==='denied'?t('Notiz gespeichert. Benachrichtigungen sind nicht erlaubt. Fällige Notizen stehen weiterhin hier; du kannst Benachrichtigungen in den iPhone-Einstellungen erlauben.','Note saved. Notifications are not allowed. Due notes still appear here; you can allow notifications in iPhone Settings.'):status==='scheduled'?t('Notiz gespeichert. Die nächste Geräte-Erinnerung ist eingerichtet.','Note saved. The next device reminder is scheduled.'):t('Notizen gespeichert.','Notes saved.');
  });
  const [later,setLater]=useState(false),[done,setDone]=useState(false),[form,setForm]=useState(initialAdd),[text,setText]=useState(''),[date,setDate]=useState(''),[editing,setEditing]=useState<string>();
  const display=(iso:string)=>iso?`${iso.slice(8,10)}.${iso.slice(5,7)}.${iso.slice(0,4)}`:'';
  const iso=(value:string)=>{const m=value.match(/^(\d{2})\.(\d{2})\.(\d{4})$/);return value?m?`${m[3]}-${m[2]}-${m[1]}`:'invalid':'';};
  const dateLabel=(value:string)=>new Intl.DateTimeFormat(de?'de-AT':'en-GB',{day:'numeric',month:'short',year:'numeric',timeZone:'UTC'}).format(new Date(`${value}T12:00:00Z`));
  function start(memo?:HomeMemo){c.clear();setEditing(memo?.id);setText(memo?.text??'');setDate(display(memo?.date??''));setForm(true);}
  async function submit(){if(await c.save(text,iso(date),editing)){setForm(false);setText('');setDate('');setEditing(undefined);Keyboard.dismiss();}}
  function rows(items:HomeMemo[]){return items.map(m=><View key={m.id} style={s.row}><Pressable accessibilityRole="checkbox" accessibilityState={{checked:m.done,disabled:c.busy}} disabled={c.busy} accessibilityLabel={`${m.text} · ${t('Erledigt','Done')}`} onPress={()=>void c.toggle(m.id)} style={s.memo}><View style={[s.check,m.done&&s.checked]}><Text style={s.checkText}>{m.done?'✓':''}</Text></View><View style={s.copy}><Text style={[s.text,m.done&&s.finished]}>{m.text}</Text>{m.date&&<Text style={[s.small,!m.done&&m.date<=c.today&&s.due]}>{!m.done&&m.date<=c.today?`${t('Fällig','Due')} · `:''}{dateLabel(m.date)}</Text>}</View></Pressable><View style={s.actions}><Pressable accessibilityRole="button" disabled={c.busy} accessibilityLabel={`${m.text} · ${t('Bearbeiten','Edit')}`} onPress={()=>start(m)} style={s.action}><Text style={s.link}>{t('Bearbeiten','Edit')}</Text></Pressable><Pressable accessibilityRole="button" disabled={c.busy} accessibilityLabel={`${m.text} · ${t('Entfernen','Remove')}`} onPress={()=>Alert.alert(t('Notiz entfernen?','Remove note?'),m.text,[{text:t('Abbrechen','Cancel'),style:'cancel'},{text:t('Entfernen','Remove'),style:'destructive',onPress:()=>void c.remove(m.id)}])} style={s.action}><Text style={s.remove}>{t('Entfernen','Remove')}</Text></Pressable></View></View>);}
  return <View style={s.section} accessibilityLabel={t('Merken & erinnern','Notes & reminders')}>
    <Pressable accessibilityRole="button" accessibilityState={{expanded:open}} onPress={onToggle} style={s.summary}><View style={s.copy}><Text style={s.heading}>{t('Merken & erinnern','Notes & reminders')}</Text><Text style={s.small}>{c.due.length?`${c.due.length} ${t('fällig','due')}`:c.memos.some(m=>!m.done)?`${c.memos.filter(m=>!m.done).length} ${t('offen','open')}`:t('Eine Idee für später festhalten','Keep an idea for later')}</Text></View><DisclosureIcon open={open}/></Pressable>
    {open&&<View style={s.body}>{rows(c.current)}{!c.current.length&&<Text style={s.note}>{t('Keine offenen Notizen für diesen Monat.','No open notes for this month.')}</Text>}
      {c.later.length>0&&<><Pressable accessibilityRole="button" accessibilityState={{expanded:later}} onPress={()=>setLater(!later)} style={s.disclosure}><Text style={s.link}>{t('Später','Later')} ({c.later.length})</Text><DisclosureIcon open={later}/></Pressable>{later&&rows(c.later)}</>}
      {c.done.length>0&&<><Pressable accessibilityRole="button" accessibilityState={{expanded:done}} onPress={()=>setDone(!done)} style={s.disclosure}><Text style={s.link}>{t('Erledigt','Done')} ({c.done.length})</Text><DisclosureIcon open={done}/></Pressable>{done&&rows(c.done)}</>}
      <Pressable accessibilityRole="button" disabled={c.busy} onPress={()=>start()} style={s.add}><Text style={s.addText}>{t('Notiz hinzufügen','Add note')}</Text></Pressable>
      {form&&<FormSection onSave={submit} saveLabel={t('Notiz speichern','Save note')} style={s.form}>
        <FormInput label={t('Notiz','Note')} value={text} onChangeText={setText} autoFocus multiline submitBehavior="newline" maxLength={300} editable={!c.busy} placeholder={t('Drei Abos auf Jahreszahlung prüfen','Review annual billing for three subscriptions')} style={s.textInput}/>
        <FormInput label={t('Erinnern am (optional)','Reminder date (optional)')} value={date} onChangeText={value=>{const digits=value.replace(/\D/g,'').slice(0,8);setDate(digits.replace(/^(\d{2})(\d)/,'$1.$2').replace(/^(\d{2}\.\d{2})(\d)/,'$1.$2'));}} keyboardType="number-pad" maxLength={10} editable={!c.busy} placeholder={de?'TT.MM.JJJJ':'DD.MM.YYYY'}/>
        <View style={s.quick}>{[[c.today,t('Heute','Today')],[`${c.today.slice(0,4)}-12-31`,t('Jahresende','Year end')],['',t('Ohne Datum','No date')]].map(([value,label])=><Pressable key={label} accessibilityRole="button" disabled={c.busy} onPress={()=>{setDate(display(value));Keyboard.dismiss();}} style={s.quickButton}><Text style={s.link}>{label}</Text></Pressable>)}</View>
        <Text style={s.small}>{t('Mit Datum: Erinnerung um 09:00 Uhr auf diesem Gerät, wenn Benachrichtigungen erlaubt sind. Bereits fällige Notizen siehst du hier.','With a date: a 9am reminder on this device if notifications are allowed. Notes already due appear here.')}</Text>
        <View style={s.quick}><FormSubmitButton label={t('Notiz speichern','Save note')} style={s.add} textStyle={s.addText}/><Pressable accessibilityRole="button" disabled={c.busy} onPress={()=>{setForm(false);c.clear();Keyboard.dismiss();}} style={s.action}><Text style={s.link}>{t('Abbrechen','Cancel')}</Text></Pressable></View>
      </FormSection>}
      {c.error&&<Text accessibilityRole="alert" style={s.error}>{c.error}</Text>}{c.notice&&<Text accessibilityLiveRegion="polite" style={s.note}>{c.notice}</Text>}
    </View>}
  </View>;
}
const s=StyleSheet.create({section:{borderWidth:1,borderColor:'#dfe5dd',borderRadius:16,backgroundColor:'#f4f6f2',marginBottom:16},summary:{minHeight:64,padding:16,flexDirection:'row',alignItems:'center',gap:12},copy:{flex:1,gap:4},heading:{fontSize:13,fontWeight:'600',color:'#17211f'},small:{fontSize:11,lineHeight:18,color:'#65716d'},body:{paddingHorizontal:16,paddingBottom:16,gap:10,borderTopWidth:1,borderTopColor:'#dfe5dd'},row:{borderBottomWidth:1,borderBottomColor:'#e7ebe5',paddingTop:12},memo:{minHeight:44,flexDirection:'row',gap:12,alignItems:'flex-start'},check:{width:24,height:24,borderWidth:1,borderColor:'#65716d',borderRadius:6,alignItems:'center',justifyContent:'center'},checked:{backgroundColor:'#28734d',borderColor:'#28734d'},checkText:{fontSize:16,color:'#fff'},text:{fontSize:13,fontWeight:'600',lineHeight:20,color:'#17211f'},finished:{textDecorationLine:'line-through',color:'#65716d'},due:{color:'#28734d',fontWeight:'600'},actions:{marginLeft:32,flexDirection:'row',gap:10},action:{minHeight:44,justifyContent:'center',paddingHorizontal:4},link:{fontSize:11,fontWeight:'600',color:'#52605b'},remove:{fontSize:11,color:'#9a7777'},disclosure:{minHeight:44,flexDirection:'row',alignItems:'center',justifyContent:'space-between'},note:{fontSize:12,lineHeight:19,color:'#65716d',marginTop:8},add:{minHeight:44,alignSelf:'flex-start',justifyContent:'center',paddingHorizontal:14,borderRadius:24,backgroundColor:'#ddf8e9'},addText:{fontSize:12,fontWeight:'700',color:'#087a45'},form:{gap:12,padding:12,borderWidth:1,borderColor:'#dfe5dd',borderRadius:12,backgroundColor:'#fff'},textInput:{minHeight:88,paddingTop:12,textAlignVertical:'top'},quick:{flexDirection:'row',flexWrap:'wrap',gap:8},quickButton:{minHeight:44,paddingHorizontal:10,justifyContent:'center',borderWidth:1,borderColor:'#dfe5dd',borderRadius:24},error:{fontSize:12,lineHeight:19,color:'#b42318'}});
