import {useState} from 'react';
import {DisclosureIcon} from './BrandMotion';
import {Pressable,StyleSheet,Text,View} from 'react-native';
import {usePaymentChecklist} from '@eavesence/core/usePaymentChecklist';
import {paymentKey} from '@eavesence/core/paymentChecklist';
import type {HouseholdCost} from '@eavesence/core/householdCosts';
import type {PlanningData} from '@eavesence/core/planning';
type Props={costs:HouseholdCost[];data?:PlanningData;onSave:(data:PlanningData)=>void|Promise<void>;locale:'de'|'en';currency:string;onEdit:(cost:HouseholdCost)=>void;onAdd:()=>void;onPlan?:()=>void};
export function MonthlyPayments({costs,data,onSave,locale,currency,onEdit,onAdd,onPlan}:Props){
 const [paidOpen,setPaidOpen]=useState(false),de=locale==='de',t=(a:string,b:string)=>de?a:b;
 const c=usePaymentChecklist(costs,data,onSave,de),paid=c.payments.filter(p=>c.isPaid(p));
 const money=(n:number)=>new Intl.NumberFormat(de?'de-AT':'en-GB',{style:'currency',currency}).format(n);
 const monthLabel=new Intl.DateTimeFormat(de?'de-AT':'en-GB',{month:'long',year:'numeric',timeZone:'UTC'}).format(new Date(`${c.month}-01T12:00:00Z`));
 const dateLabel=(d:string)=>new Intl.DateTimeFormat(de?'de-AT':'en-GB',{day:'numeric',month:'short',timeZone:'UTC'}).format(new Date(`${d}T12:00:00Z`));
 function row(p:typeof c.payments[number],priority=false){const checked=c.isPaid(p);return <View key={paymentKey({costId:p.cost.id,month:p.month,date:p.date})} style={[s.row,priority&&s.priorityRow]}>
  <Pressable accessibilityRole="checkbox" accessibilityState={{checked,disabled:c.busy}} accessibilityLabel={`${p.cost.name}, ${p.date?dateLabel(p.date):monthLabel}, ${money(p.cost.amount)}, ${t('Bezahlt','Paid')}`} disabled={c.busy} onPress={()=>void c.toggle(p)} style={s.checkTarget}><View style={[s.check,checked&&s.checked]}><Text style={s.checkText}>{checked?'✓':''}</Text></View></Pressable>
  <Pressable accessibilityRole="button" accessibilityLabel={`${p.cost.name} · ${t('Bearbeiten','Edit')}`} onPress={()=>onEdit(p.cost)} style={s.payment}><View style={s.nameColumn}><Text style={[s.name,checked&&s.paidName]}>{p.cost.name}</Text><Text style={s.small}>{p.date?dateLabel(p.date):t('Monatlich · Termin fehlt','Monthly · date missing')}{p.date&&p.date<c.today&&!checked?` · ${t('überfällig','overdue')}`:''}</Text></View><Text style={[s.value,checked&&s.paidName]}>{money(p.cost.amount)}</Text><Text style={s.chevron}>›</Text></Pressable>
 </View>;}
 const upcoming=c.open.filter(p=>p!==c.nextDue);
 return <View style={s.section} accessibilityLabel={t('Monatscheckliste','Monthly checklist')}>
  <View style={s.monthRow}><Pressable accessibilityRole="button" accessibilityLabel={t('Vorheriger Monat','Previous month')} onPress={c.previous} style={s.arrow}><Text style={s.arrowText}>‹</Text></Pressable><Text accessibilityRole="header" style={s.title}>{monthLabel}</Text><Pressable accessibilityRole="button" accessibilityLabel={t('Nächster Monat','Next month')} onPress={c.next} style={s.arrow}><Text style={s.arrowText}>›</Text></Pressable></View>
  {c.month!==c.current&&<Pressable accessibilityRole="button" onPress={c.reset} style={s.today}><Text style={s.link}>{t('Zum aktuellen Monat','Back to this month')}</Text></Pressable>}
  <View style={s.summary}><View style={s.metric}><Text style={s.caption}>{t('Noch offen','Still unpaid')}{c.missing.length?` · ${t('unvollständig','incomplete')}`:''}</Text><Text style={s.amount} accessibilityLiveRegion="polite">{c.payments.length?money(c.openTotal):'—'}</Text></View><View style={[s.metric,s.paidMetric]}><Text style={s.caption}>{t('Bezahlt','Paid')}</Text><Text style={s.amount}>{money(c.paidTotal)}</Text></View></View>
  {c.nextDue&&<View style={s.priority}><Text style={s.eyebrow}>{t('Nächste Zahlung','Next payment')}</Text>{row(c.nextDue,true)}</View>}
  {c.payments.length>0&&<View style={s.progress}><Text style={s.small}>{`${paid.length} ${t('von','of')} ${c.payments.length} ${t('Zahlungen erledigt','payments done')}`}</Text><View accessibilityRole="progressbar" accessibilityValue={{min:0,max:c.payments.length,now:paid.length}} style={s.track}><View style={[s.fill,{width:`${paid.length/c.payments.length*100}%`}]}/></View></View>}
  {upcoming.length>0&&<><Text style={s.heading}>{t('Anstehende Zahlungen','Upcoming payments')}</Text>{upcoming.map(p=>row(p))}</>}
  {!c.open.length&&c.payments.length>0&&<Text style={s.note}>{t('Alle erfassten Zahlungen dieses Monats sind abgehakt.','All recorded payments for this month are checked off.')}</Text>}
  {!c.payments.length&&<Text style={s.note}>{costs.length?t('Keine Zahlungen für diesen Monat eingeplant.','No payments scheduled for this month.'):t('Füge deine erste regelmäßige Ausgabe hinzu.','Add your first recurring cost.')}</Text>}
  {paid.length>0&&<><Pressable accessibilityRole="button" accessibilityState={{expanded:paidOpen}} onPress={()=>setPaidOpen(!paidOpen)} style={s.disclosure}><Text style={s.heading}>{t('Bezahlte Zahlungen','Paid payments')} · {paid.length}</Text><DisclosureIcon open={paidOpen}/></Pressable>{paidOpen&&paid.map(p=>row(p))}</>}
  {c.error&&<Text accessibilityRole="alert" style={s.error}>{c.error}</Text>}
  {c.missing.length>0&&<View style={s.missing}><Text style={s.note}>{t('Diese Kosten brauchen einen Termin. Sie fehlen im offenen Betrag.','These costs need a date. They are excluded from the unpaid amount.')}</Text>{c.missing.map(cost=><Pressable accessibilityRole="button" key={cost.id} onPress={()=>onEdit(cost)} style={s.today}><Text style={s.link}>{cost.name} · {t('Termin ergänzen','Add date')}</Text></Pressable>)}</View>}
  {c.payments.some(p=>!p.date)&&<Text style={s.note}>{t('Monatliche Kosten ohne Termin zählen einmal pro Monat.','Monthly costs without a date count once each month.')}</Text>}
  <Text style={s.small}>{t('Hake ab, was bezahlt wurde. Ohne Bankabgleich.','Check off what is paid. No bank connection.')}</Text>
  {!costs.length&&<Pressable accessibilityRole="button" onPress={onAdd} style={s.today}><Text style={s.link}>{t('Kosten hinzufügen','Add cost')}</Text></Pressable>}
  {onPlan&&<Pressable accessibilityRole="button" onPress={onPlan} style={s.plan}><Text style={s.name}>{t('Bis zum Gehalt planen','Plan until payday')}</Text><Text style={s.badge}>Pro</Text><Text style={s.chevron}>›</Text></Pressable>}
 </View>;
}
const s=StyleSheet.create({
 section:{gap:12,marginBottom:20},monthRow:{flexDirection:'row',alignItems:'center',gap:8},title:{flex:1,fontSize:22,fontWeight:'700',textAlign:'center',color:'#17211f'},arrow:{minWidth:44,minHeight:44,alignItems:'center',justifyContent:'center'},arrowText:{fontSize:30,color:'#17211f'},today:{minHeight:44,justifyContent:'center'},
 summary:{flexDirection:'row',padding:20,borderRadius:18,backgroundColor:'#24272c'},metric:{flex:1,minWidth:0,gap:8},paidMetric:{borderLeftWidth:1,borderColor:'#59625d',paddingLeft:16,marginLeft:12},caption:{fontSize:13,lineHeight:19,color:'#d1d7d4'},amount:{fontSize:24,fontWeight:'700',letterSpacing:-.5,color:'#fff',flexShrink:1},
 priority:{backgroundColor:'#e6f5ed',borderRadius:16,paddingHorizontal:14,paddingTop:14},eyebrow:{fontSize:11,fontWeight:'600',letterSpacing:.8,color:'#28734d',textTransform:'uppercase'},priorityRow:{borderBottomWidth:0},row:{flexDirection:'row',alignItems:'center',borderBottomWidth:1,borderColor:'#e3e8e2'},checkTarget:{minWidth:44,minHeight:60,alignItems:'center',justifyContent:'center'},check:{width:23,height:23,borderRadius:6,borderWidth:1.5,borderColor:'#52605b'},checked:{backgroundColor:'#28734d',borderColor:'#28734d'},checkText:{color:'#fff',fontSize:16,textAlign:'center',fontWeight:'700'},payment:{flex:1,minHeight:60,flexDirection:'row',alignItems:'center',gap:10,paddingVertical:10},nameColumn:{flex:1,minWidth:0},name:{fontSize:15,lineHeight:21,fontWeight:'600',color:'#17211f'},value:{fontSize:15,fontWeight:'600',color:'#17211f',flexShrink:1,maxWidth:'38%'},paidName:{textDecorationLine:'line-through',color:'#65716d'},small:{fontSize:12,lineHeight:19,color:'#65716d'},chevron:{fontSize:22,color:'#65716d'},heading:{fontSize:14,fontWeight:'600',color:'#17211f'},progress:{gap:7},track:{height:6,borderRadius:4,backgroundColor:'#e2e7e1',overflow:'hidden'},fill:{height:6,backgroundColor:'#28734d',borderRadius:4},disclosure:{minHeight:52,flexDirection:'row',justifyContent:'space-between',alignItems:'center',gap:12},note:{fontSize:13,lineHeight:20,color:'#65716d'},error:{fontSize:13,lineHeight:20,color:'#b42318'},missing:{padding:14,backgroundColor:'#fff5df',borderRadius:14},link:{fontSize:13,fontWeight:'600',color:'#28734d'},plan:{minHeight:56,flexDirection:'row',alignItems:'center',gap:12,paddingHorizontal:14,borderRadius:14,backgroundColor:'#edf0ec',marginTop:4},badge:{fontSize:11,fontWeight:'600',color:'#28734d',backgroundColor:'#dcf8e8',paddingHorizontal:8,paddingVertical:3,borderRadius:10,marginLeft:'auto'},
});
