import { useState } from 'react';
import { Alert, Pressable, StyleSheet, View } from 'react-native';
import { usePlanning } from '@eavesence/core/usePlanning';
import { shiftPlanningMonth, type PlanningData } from '@eavesence/core/planning';
import type { SavingsPlanInput } from '@eavesence/core/savingsPlan';
import { LocalizedText as Text, useMobileLocale } from './i18n';
import { FormInput } from './FormInput';

export function PlanningScreen({input,data,onSave,currency,onEditCosts,onEditBudget}:{input:SavingsPlanInput;data?:PlanningData;onSave:(data:PlanningData)=>Promise<void>;currency:string;onEditCosts:()=>void;onEditBudget:()=>void}) {
 const de=useMobileLocale()==='de';const p=usePlanning(input,data,onSave,de);
 const [open,setOpen]=useState<string|null>(null);
 const money=(n:number)=>new Intl.NumberFormat(de?'de-AT':'en-GB',{style:'currency',currency}).format(n);
 const month=(s:string)=>new Intl.DateTimeFormat(de?'de-AT':'en-GB',{month:'long',year:'numeric',timeZone:'UTC'}).format(new Date(`${s}-01T00:00:00Z`));
 const toggle=(key:string,title:string)=><Pressable accessibilityRole="button" accessibilityState={{expanded:open===key}} onPress={()=>setOpen(open===key?null:key)} style={styles.toggle}><Text style={styles.title}>{title}</Text><Text style={styles.note}>{open===key?'−':'+'}</Text></Pressable>;
 const button=(label:string,action:()=>void,disabled=false)=><Pressable accessibilityRole="button" disabled={disabled||p.busy} onPress={action} style={[styles.button,(disabled||p.busy)&&styles.disabled]}><Text style={styles.buttonText}>{label}</Text></Pressable>;
 const monthPicker=(label:string,value:string,set:(v:string)=>void,limit=false)=><View style={styles.box}><Text style={styles.note}>{label}: {month(value)}</Text><View style={styles.row}>{button(de?'Vorheriger Monat':'Previous month',()=>set(shiftPlanningMonth(value,-1)),limit&&value<=input.startMonth)}{button(de?'Nächster Monat':'Next month',()=>set(shiftPlanningMonth(value,1)),limit&&value>=shiftPlanningMonth(input.startMonth,11))}</View></View>;
 return <View style={styles.container}>
  <View style={styles.card}>
   <Text style={styles.title}>{de?'Dein Monatscheck':'Your monthly check'}</Text><Text style={styles.note}>{de?'Prüfe nur, was sich geändert hat. Deine bisherigen Angaben bleiben erhalten.':'Review only what changed. Your existing entries stay in place.'}</Text>
   {!p.canCheck?<Text style={styles.note}>{de?'Ergänze zuerst Einkommen, mindestens eine Fixkostenausgabe und deine Alltagsschätzung.':'First add income, at least one fixed cost and your everyday-spending estimate.'}</Text>:p.reviewed?<Text style={styles.good}>{de?'Für diesen Monat geprüft. Budgetänderungen öffnen den Check erneut.':'Reviewed this month. Budget changes reopen the check.'}</Text>:<>
    {[de?`Einkommen passt: ${money(input.incomeMonthly)}`:`Income is current: ${money(input.incomeMonthly)}`,de?`Fixkosten geprüft: ${money(p.plan?.averageFixed??0)} im Monatsdurchschnitt`:`Fixed costs reviewed: ${money(p.plan?.averageFixed??0)} monthly average`,de?`Alltagsschätzung passt: ${money(input.variableMonthly??0)}`:`Everyday estimate is current: ${money(input.variableMonthly??0)}`].map((label,i)=><Pressable key={i} accessibilityRole="checkbox" accessibilityState={{checked:p.checks[i]}} style={styles.check} onPress={()=>p.setChecks(p.checks.map((v,n)=>n===i?!v:v))}><Text style={styles.note}>{p.checks[i]?'✓':'○'} {label}</Text></Pressable>)}
    {button(de?'Monatscheck abschließen':'Complete monthly check',()=>void p.finishCheck(),!p.checks.every(Boolean))}
   </>}
   {button(de?'Einkommen oder Kosten ändern':'Update income or costs',onEditCosts)}{button(de?'Alltagsschätzung ändern':'Update everyday estimate',onEditBudget)}
   {p.data.checks.slice(0,3).map(c=><Text key={c.month} style={styles.note}>{month(c.month)} · {de?'Rest nach Fixkosten und Alltag':'Left after fixed costs and everyday spending'}: {money(c.incomeMonthly-c.fixedMonthly-c.variableMonthly)}</Text>)}
  </View>
  <View style={styles.card}>{toggle('goals',de?'Sparziele mit Zweck und Datum':'Savings goals with a purpose and date')}{open==='goals'&&<>
   <Text style={styles.note}>{de?'Trage nur tatsächlich für dieses Ziel zurückgelegtes Geld ein. Ziele verteilen deinen Sparbetrag und werden nicht zusätzlich abgezogen.':'Only enter money actually set aside for this goal. Goals allocate your savings amount and are not deducted again.'}</Text>
   {p.goals.map(g=><View key={g.id} style={styles.box}><Text style={styles.title}>{g.name}</Text><Text style={styles.note}>{money(g.saved)} / {money(g.target)} · {month(g.targetMonth)}</Text><View accessibilityRole="progressbar" accessibilityValue={{min:0,max:100,now:Math.round(g.percent)}} style={styles.track}><View style={[styles.progress,{width:`${g.percent}%`}]}/></View><Text style={styles.note}>{g.remaining===0?(de?'Ziel erreicht.':'Goal reached.'):g.overdue?(de?'Zieldatum vorbei. Datum anpassen.':'Target date passed. Update the date.'):`${de?'Noch nötig':'Still needed'}: ${money(g.monthly)} ${de?'pro Monat':'per month'}`}</Text>{button(de?'Guthaben / Ziel ändern':'Update balance / goal',()=>p.editGoal(g))}{button(de?'Entfernen':'Remove',()=>Alert.alert(de?'Sparziel entfernen?':'Remove savings goal?',de?'Dein tatsächliches Guthaben bleibt unverändert.':'Your actual savings remain unchanged.',[{text:de?'Abbrechen':'Cancel',style:'cancel'},{text:de?'Entfernen':'Remove',onPress:()=>void p.persist({...p.data,goals:p.data.goals.filter(x=>x.id!==g.id)})}]))}</View>)}
   {p.goals.length>0&&<Text style={styles.note}>{de?'Für alle Ziele nötig':'Needed for all goals'}: {money(p.required)} {de?'pro Monat. Eingetragener Sparbetrag':'per month. Your savings amount'}: {money(input.goalMonthly)}. {p.required>input.goalMonthly?(de?'Sparbetrag oder Zieldaten anpassen.':'Adjust savings amount or target dates.'):(de?'Dein Sparbetrag deckt die Beiträge.':'Your savings amount covers the contributions.')}</Text>}
   <FormInput label={de?'Name des Sparziels':'Goal name'} value={p.name} onChangeText={p.setName} placeholder={de?'z. B. Urlaub':'e.g. Holiday'}/><FormInput label={de?'Zielbetrag':'Target amount'} value={p.target} onChangeText={p.setTarget} keyboardType="decimal-pad"/><FormInput label={de?'Für dieses Ziel bereits zurückgelegt':'Already set aside for this goal'} value={p.saved} onChangeText={p.setSaved} keyboardType="decimal-pad" placeholder="0"/>
   {monthPicker(de?'Zielmonat':'Target month',p.targetMonth,p.setTargetMonth)}{button(p.editing?(de?'Ziel aktualisieren':'Update goal'):(de?'Sparziel speichern':'Save savings goal'),()=>void p.saveGoal())}{p.editing&&button(de?'Abbrechen':'Cancel',()=>p.editGoal())}
  </>}</View>
  <View style={styles.card}>{toggle('reserves',de?'Größere Rechnungen vorbereiten':'Prepare for larger bills')}{open==='reserves'&&<>
   <Text style={styles.note}>{de?'Diese Rechnungen stehen bereits in den Fixkosten und werden nicht erneut abgezogen. Halte Rücklagen getrennt von Sparzielen.':'These bills are already included in fixed costs and are not deducted again. Keep reserves separate from savings goals.'}</Text>
   {!p.reserves.length&&<Text style={styles.note}>{de?'Erfasse eine jährliche, halbjährliche oder quartalsweise Rechnung.':'Add a yearly, half-yearly or quarterly bill.'}</Text>}
   {p.reserves.map(r=><View key={r.cost.id} style={styles.box}><Text style={styles.title}>{r.cost.name} · {money(r.cost.amount)}</Text><Text style={styles.note}>{r.dueMonth?`${de?'Fällig':'Due'}: ${month(r.dueMonth)} · ${de?'Bis dahin zurücklegen':'Set aside until then'}: ${money(r.monthly??0)} ${de?'pro Monat':'per month'}`:(de?'Zahlungstermin ergänzen, um den Rücklagenplan zu berechnen.':'Add a payment date to calculate the reserve plan.')}</Text><FormInput label={de?'Für diese Rechnung bereits zurückgelegt':'Already set aside for this bill'} value={p.reserveDraft[r.cost.id]??String(r.saved)} onChangeText={v=>p.setReserveDraft({...p.reserveDraft,[r.cost.id]:v})} keyboardType="decimal-pad"/>{button(de?'Rücklage speichern':'Save set-aside amount',()=>void p.saveReserve(r.cost.id))}</View>)}
  </>}</View>
  <View style={styles.card}><Text style={styles.title}>{de?'Deine nächsten sinnvollen Schritte':'Your next useful steps'}</Text>{!p.suggestions.length&&<Text style={styles.note}>{de?'Aktuell kein dringender Hinweis aus deinen Angaben.':'No urgent suggestions from your current entries.'}</Text>}{p.suggestions.map((s,i)=><View key={i} style={styles.box}><Text style={styles.note}>{s.kind==='dates'?(de?'Zahlungstermine fehlen. Ergänze sie für eine vollständige Vorschau.':'Payment dates are missing. Add them for a complete forecast.'):s.kind==='deadline'?`${s.name}: ${de?'Kündigungsfrist prüfen bis':'Review cancellation deadline by'} ${s.date}`:s.kind==='tight'?`${de?'Im':'In'} ${month(s.month!)} ${de?'wird der Plan nach deinem Sparbetrag negativ. Prüfe Ziel und Ausgaben.':'your plan falls below zero after savings. Review your goal and spending.'}`:`${s.name}: ${de?'Prüfe, ob ein günstigerer Betrag möglich ist. Es ist noch keine Ersparnis eingerechnet.':'Check whether a lower payment is possible. No saving is assumed yet.'}`}</Text>{button(de?'Angaben prüfen':'Review entries',s.kind==='tight'?onEditBudget:onEditCosts)}</View>)}</View>
  <View style={styles.card}>{toggle('purchase',de?'Eine Anschaffung durchspielen':'Try a one-off purchase')}{open==='purchase'&&<>
   <Text style={styles.note}>{de?'Diese Vorschau verändert keine Kosten und führt keine Zahlung aus. Sie zeigt den Monatsplan, nicht deinen Kontostand.':'This preview changes no costs and makes no payment. It shows your monthly plan, not your bank balance.'}</Text>
   <FormInput label={de?'Anschaffung':'Purchase'} value={p.purchaseName} onChangeText={p.setPurchaseName} placeholder={de?'z. B. Waschmaschine':'e.g. Washing machine'}/><FormInput label={de?'Einmaliger Betrag':'One-off amount'} value={p.purchaseAmount} onChangeText={p.setPurchaseAmount} keyboardType="decimal-pad"/>{monthPicker(de?'Kaufmonat':'Purchase month',p.purchaseMonth,p.setPurchaseMonth,true)}<FormInput label={de?'Für den Kauf verfügbares Guthaben (optional)':'Funds available for this purchase (optional)'} value={p.available} onChangeText={p.setAvailable} keyboardType="decimal-pad"/><Text style={styles.note}>{de?'Nur frei verfügbares Geld, ohne bereits reservierte Beträge.':'Only unallocated money, excluding amounts already reserved.'}</Text>
   {p.impact?<View style={styles.box}><Text style={styles.title}>{p.purchaseName||(de?'Deine Anschaffung':'Your purchase')}</Text><Text style={styles.note}>{de?'Rest nach Sparbetrag, vor Kauf':'Left after savings, before purchase'}: {money(p.impact.before)}</Text><Text style={styles.title}>{de?'Nach dem Kauf im Monatsplan':'After purchase in the monthly plan'}: {money(p.impact.after)}</Text>{p.impact.after<0&&<Text style={styles.note}>{de?'Für deinen unveränderten Plan fehlen':'Your unchanged plan falls short by'} {money(-p.impact.after)}. {p.impact.later?`${de?'Späterer Monat mit ausreichendem Plan-Spielraum':'A later month with enough planned room'}: ${month(p.impact.later)}.`:(de?'Kein passender Monat in dieser Vorschau.':'No suitable month in this preview.')}</Text>}{p.impact.goalShortfall>0&&<Text style={styles.note}>{de?"Wenn du den Kauf aus diesem Monatsbudget deckst, fehlen für deinen Sparbetrag":"If funded from this month’s budget, your savings contribution falls short by"}: {money(p.impact.goalShortfall)}. {input.goalMonthly>0&&`${de?"Bei gleicher Sparrate entspricht das rechnerisch bis zu":"At the same savings rate, that represents up to"} ${Math.ceil(p.impact.goalShortfall/input.goalMonthly)} ${de?"zusätzlichem Sparmonat.":"extra savings month."}`}</Text>}{p.impact.availableAfter!==null&&<Text style={styles.note}>{de?'Von deinem angegebenen Guthaben bleiben':'Your entered available funds would become'}: {money(p.impact.availableAfter)}.</Text>}<Text style={styles.note}>{de?'Vorhandene Rücklagen können ein negatives Monatsergebnis decken. Guthaben und Monatsrest werden hier nicht zusammengerechnet.':'Existing savings may cover a negative monthly result. Available funds and monthly room are not added together here.'}</Text></View>:<Text style={styles.note}>{de?'Ergänze Einkommen, Alltagsschätzung und einen gültigen Kaufbetrag über 0.':'Add income, an everyday estimate and a valid positive purchase amount.'}</Text>}
  </>}</View>
  {!!p.error&&<Text accessibilityRole="alert" style={styles.error}>{p.error}</Text>}{!!p.notice&&<Text accessibilityRole="alert" style={styles.good}>{p.notice}</Text>}
 </View>;
}
const styles=StyleSheet.create({container:{gap:12,marginTop:16},card:{borderRadius:14,padding:14,backgroundColor:'#ffffff',gap:10},title:{fontSize:14,fontWeight:'800',color:'#17211f'},note:{fontSize:12,lineHeight:18,color:'#52605b'},good:{fontSize:12,lineHeight:18,fontWeight:'700',color:'#087a45'},error:{fontSize:13,color:'#b91c1c'},button:{alignSelf:'flex-start',minHeight:36,paddingHorizontal:12,paddingVertical:8,borderRadius:18,backgroundColor:'#dff7e9',justifyContent:'center'},buttonText:{fontSize:12,fontWeight:'700',color:'#087a45'},disabled:{opacity:0.45},row:{flexDirection:'row',flexWrap:'wrap',gap:10},box:{borderRadius:12,padding:12,gap:8,backgroundColor:'#eefbf3'},toggle:{minHeight:36,flexDirection:'row',alignItems:'center',justifyContent:'space-between',gap:10},check:{minHeight:44,justifyContent:'center'},track:{height:6,borderRadius:3,backgroundColor:'#dfe5dd',overflow:'hidden'},progress:{height:6,backgroundColor:'#087a45'}});
