import { useState } from 'react';
import { Pressable, StyleSheet, View } from 'react-native';
import { useProTools } from '@eavesence/core/useProTools';
import type { PlanningData } from '@eavesence/core/planning';
import type { SavingsPlanInput } from '@eavesence/core/savingsPlan';
import { DisclosureIcon } from './BrandMotion';
import { FormInput } from './FormInput';
import { FormSection, FormSubmitButton } from './FormSection';
import { LocalizedText as Text, useMobileLocale } from './i18n';
function displayDate(value:string){return /^\d{4}-\d{2}-\d{2}$/.test(value)?value.split('-').reverse().join('.'):value;}
function dateInput(value:string){const d=value.replace(/\D/g,'').slice(0,8);return d.length===8?`${d.slice(4)}-${d.slice(2,4)}-${d.slice(0,2)}`:[d.slice(0,2),d.slice(2,4),d.slice(4)].filter(Boolean).join('.');}
export function ProToolsScreen({input,data,onSave,onReview,currency}:{input:SavingsPlanInput;data?:PlanningData;onSave:(p:PlanningData)=>Promise<void>;onReview:(c:SavingsPlanInput['costs'][number])=>void;currency:string}) {
  const de=useMobileLocale()==='de',t=(a:string,b:string)=>de?a:b,p=useProTools(input,data,onSave,de),[open,setOpen]=useState<'reserves'|'annual'|null>(null);
  const money=(n:number)=>new Intl.NumberFormat(de?'de-AT':'en-GB',{style:'currency',currency}).format(n);
  const day=(s:string)=>new Intl.DateTimeFormat(de?'de-AT':'en-GB',{day:'numeric',month:'long',year:'numeric',timeZone:'UTC'}).format(new Date(`${s}T00:00:00Z`));
  const button=(label:string,onPress:()=>void)=><Pressable accessibilityRole="button" disabled={p.busy} style={styles.button} onPress={onPress}><Text style={styles.buttonText}>{label}</Text></Pressable>;
  const toggle=(key:'reserves'|'annual',title:string)=><Pressable accessibilityRole="button" accessibilityState={{expanded:open===key}} style={styles.disclosure} onPress={()=>setOpen(open===key?null:key)}><Text style={styles.title}>{title}</Text><DisclosureIcon open={open===key}/></Pressable>;
  return <View style={styles.container}>
    <View style={styles.card}>{toggle('reserves',t('Jahreskosten rechtzeitig vorbereiten','Prepare for annual bills'))}{open==='reserves'&&<>
      <Text style={styles.note}>{t('Auch für Rechnungen alle drei oder sechs Monate. Der Monatsdurchschnitt ist eine Rechengröße; eine Rücklage ist Geld, das du wirklich dafür reserviert hast.','Also for quarterly and half-yearly bills. The monthly average is a calculation; a reserve is money you actually set aside.')}</Text>
      {!p.reserves.length&&<Text style={styles.note}>{t('Erfasse zuerst eine jährliche, halbjährliche oder quartalsweise Rechnung.','Add a yearly, half-yearly or quarterly bill first.')}</Text>}
      {p.reserves.map(r=><View key={r.cost.id} style={styles.box}><Text style={styles.title}>{r.cost.name}</Text><Text style={styles.note}>{r.dueDate?`${r.overdue?t('Noch offen seit','Still unpaid since'):t('Fällig am','Due on')} ${day(r.dueDate)}: ${money(r.cost.amount)}`:t('Der Zahlungstermin fehlt.','Payment date missing.')}</Text><Text style={styles.note}>{t('Bereits zurückgelegt','Already set aside')}: {money(r.saved)}</Text><Text style={styles.title}>{t('Noch erforderlich','Still needed')}: {money(r.missing)}</Text>
        {r.monthly!==null&&<Text style={styles.good}>{r.missing===0?t('Für diese Rechnung vollständig zurückgelegt.','Fully set aside for this bill.'):r.months===1?`${t('Diesen Monat noch zurücklegen','Still set aside this month')}: ${money(r.missing)}`:`${money(r.monthly)} ${t('pro Monat ab diesem Monat bis zur Fälligkeit','per month from this month until due')} (${r.months}).`}</Text>}
        <Text style={styles.note}>{t('Zum Vergleich: Monatsdurchschnitt','For comparison: monthly average')} {money(r.average)}. {t('Kein zusätzlicher Kostenabzug. Nach dem Abhaken gilt die Rücklage für den nächsten Termin wieder als 0.','No additional cost deduction. Once checked paid, the next payment starts with 0 set aside.')}</Text>
        <FormSection onSave={()=>p.saveReserve(r.cost.id)} saveLabel={t('Rücklage speichern','Save reserve')} style={styles.form}><FormInput label={t('Für diese Rechnung reserviertes Geld','Money reserved for this bill')} value={p.reserveValue(r.cost.id)} onChangeText={v=>p.setReserveValue(r.cost.id,v)} keyboardType="decimal-pad"/><FormSubmitButton label={t('Rücklage speichern','Save reserve')} style={styles.button} textStyle={styles.buttonText}/></FormSection>{!r.dueDate&&button(t('Termin ergänzen','Add date'),()=>onReview(r.cost))}
      </View>)}
    </>}</View>
    <View style={styles.card}>{toggle('annual',t('Monatsabo oder Jahresabo?','Monthly or annual subscription?'))}{open==='annual'&&<>
      <Text style={styles.note}>{t('Vergleiche ein echtes Angebot. Ein Jahresabo kann günstiger sein, braucht aber eine Vorauszahlung und bindet dich länger.','Compare an actual offer. An annual plan can cost less, but needs an upfront payment and a longer commitment.')}</Text>
      {!p.subscriptions.length&&<Text style={styles.note}>{t('Erfasse zuerst ein monatliches Abo in der Kategorie „Verträge & Abos“.','Add a monthly cost in the Contracts & subscriptions category first.')}</Text>}
      <View style={styles.row}>{p.subscriptions.map(c=><Pressable key={c.id} accessibilityRole="button" accessibilityState={{selected:p.costId===c.id}} style={[styles.button,p.costId===c.id&&styles.selected]} onPress={()=>p.setCostId(c.id)}><Text style={styles.buttonText}>{c.name} · {money(c.amount)} {t('pro Monat','per month')}</Text></Pressable>)}</View>
      {p.selected&&<><FormInput label={t('Angebot: voller Jahrespreis','Offer: full annual price')} value={p.annual} onChangeText={p.setAnnual} keyboardType="decimal-pad"/><FormInput label={t('Jahreszahlung am (TT.MM.JJJJ)','Annual payment on (DD.MM.YYYY)')} value={displayDate(p.start)} onChangeText={v=>p.setStart(dateInput(v))} keyboardType="number-pad" maxLength={10}/>{button(t('Heute','Today'),()=>p.setStart(p.today))}
        {p.comparison?<View style={styles.box}><Text style={styles.title}>{p.comparison.annualSaving>0?`${t('Pro Jahr günstiger um','Costs less per year by')} ${money(p.comparison.annualSaving)}`:p.comparison.annualSaving<0?`${t('Pro Jahr teurer um','Costs more per year by')} ${money(-p.comparison.annualSaving)}`:t('Gleiche Kosten pro Jahr.','Same annual cost.')}</Text><Text style={styles.note}>{t('Vorauszahlung','Upfront payment')}: {money(p.comparison.upfront)}. {t('Entspricht im Durchschnitt','Equivalent monthly average')}: {money(p.comparison.monthlyEquivalent)} {t('pro Monat','per month')}.</Text><Text style={styles.note}>{p.comparison.after===null?t('Aktualisiere „Bis zum Gehalt“ für die Auswirkung auf deinen Spielraum.','Update To payday to see the effect on available money.'):p.comparison.inWindow?`${t('Nach der Umstellung bis zum Gehalt verfügbar','Available until payday after switching')}: ${money(p.comparison.after)}. ${t('Ersetzte offene Monatszahlungen','Replaced unpaid monthly charges')}: ${money(p.comparison.removed)}.`:t('Die Jahreszahlung liegt nach dem nächsten Gehalt. Dein aktueller Spielraum bleibt unverändert; plane die Vorauszahlung für später ein.','The annual payment is after your next payday. Current available money stays unchanged; prepare for the future upfront payment.')}</Text>{p.comparison.after!==null&&p.comparison.after<0&&<Text style={styles.error}>{t('Für diesen Zeitpunkt reicht dein geplanter Spielraum nicht.','Your planned available money is insufficient at this time.')}</Text>}<Text style={styles.note}>{t('Die Vorschau ersetzt Monatszahlungen ab dem gewählten Datum. Prüfe Nutzung, Bindung, automatische Verlängerung und Kündigungsfrist. Nur eine Vorschau: Es wird kein Vertrag geändert und keine Ersparnis verbucht.','The preview replaces monthly charges from the selected date. Check usage, commitment, automatic renewal and cancellation terms. Preview only: no contract changes or savings are recorded.')}</Text></View>:<Text style={styles.note}>{t('Jahrespreis über 0 und ein Datum ab heute eingeben.','Enter a positive annual price and a date from today onwards.')}</Text>}
        {p.comparison&&<><FormSection onSave={()=>p.rememberComparison(money)} saveLabel={t('Vergleich in My Home merken','Save comparison to My Home')} style={styles.form}><FormInput label={t('Entscheidung merken für (TT.MM.JJJJ)','Remember decision on (DD.MM.YYYY)')} value={displayDate(p.remindAt)} onChangeText={v=>p.setRemindAt(dateInput(v))} keyboardType="number-pad" maxLength={10}/><FormSubmitButton label={t('Vergleich in My Home merken','Save comparison to My Home')} style={styles.button} textStyle={styles.buttonText}/></FormSection>{button(t('Nach Umstellung Kosten bearbeiten','Edit costs after switching'),()=>onReview(p.selected!))}<Text style={styles.note}>{t('Als Notiz unter „Merken & erinnern“. Keine automatische Benachrichtigung.','As a note under Notes & reminders. No automatic notification.')}</Text></>}
      </>}
    </>}</View>
    {!!p.error&&<Text accessibilityRole="alert" style={styles.error}>{p.error}</Text>}{!!p.notice&&<Text accessibilityRole="alert" style={styles.good}>{p.notice}</Text>}
  </View>;
}
const styles=StyleSheet.create({container:{gap:12,marginTop:14},card:{borderWidth:1,borderColor:'#dfe5dd',borderRadius:14,padding:14,backgroundColor:'#fff',gap:10},disclosure:{minHeight:44,flexDirection:'row',alignItems:'center',justifyContent:'space-between',gap:10},title:{fontSize:14,fontWeight:'700',color:'#24272c',flexShrink:1},note:{fontSize:13,lineHeight:20,color:'#52605b'},good:{fontSize:13,lineHeight:20,fontWeight:'700',color:'#28734d'},error:{fontSize:13,lineHeight:20,color:'#b91c1c'},box:{padding:12,borderRadius:12,gap:8,backgroundColor:'#f4f6f2'},button:{minHeight:44,alignSelf:'flex-start',borderRadius:20,borderWidth:1,borderColor:'#dfe5dd',paddingHorizontal:12,paddingVertical:8,justifyContent:'center',backgroundColor:'#fff'},buttonText:{fontSize:13,fontWeight:'700',color:'#28734d'},selected:{backgroundColor:'#eefbf3',borderColor:'#28734d'},row:{flexDirection:'row',flexWrap:'wrap',gap:8},form:{gap:10}});
