import { Pressable, StyleSheet, View } from 'react-native';
import { useQuickCheck } from '@eavesence/core/useQuickCheck';
import type { PlanningData } from '@eavesence/core/planning';
import type { SavingsPlanInput } from '@eavesence/core/savingsPlan';
import { LocalizedText as Text, useMobileLocale } from './i18n';
import { DisclosureIcon } from './BrandMotion';
export function QuickCheck({input,data,onSave,onBalance,onPayments,onSavings,onReview}:{input:SavingsPlanInput;data?:PlanningData;onSave:(p:PlanningData)=>Promise<void>;onBalance:()=>void;onPayments:()=>void;onSavings?:()=>void;onReview?:(c:SavingsPlanInput['costs'][number])=>void}) {
  const de=useMobileLocale()==='de',t=(a:string,b:string)=>de?a:b,q=useQuickCheck(input,data,onSave,de);
  const button=(label:string,onPress:()=>void)=><Pressable accessibilityRole="button" style={s.button} onPress={onPress}><Text style={s.buttonText}>{label}</Text></Pressable>;
  return <View style={s.card}><Pressable accessibilityRole="button" accessibilityState={{expanded:q.open}} style={s.disclosure} onPress={()=>q.setOpen(!q.open)}><Text style={s.title}>{t('Kurzer Check','Quick check')}{q.complete?` · ${t('heute erledigt','done today')}`:''}</Text><DisclosureIcon open={q.open}/></Pressable>{q.open&&<>
    <Text style={s.note}>{t('Prüfe nur, was sich geändert hat. Deine Eingaben bleiben erhalten. Wiederhole den Check nach einer Abbuchung oder vor einer größeren Ausgabe.','Review only what changed. Your entries stay in place. Repeat after a debit or before a larger purchase.')}</Text>
    <Text style={s.title}>{t('1 · Kontostand und Zeitraum','1 · Balance and time period')}{q.current?' ✓':''}</Text>{button(t('Kontostand und Alltag prüfen','Review balance and everyday spending'),onBalance)}{!q.current&&<Text style={s.note}>{t('Aktuellen Kontostand, Gehaltstag, Alltag und fehlende Zahlungstermine ergänzen.','Update balance, payday, everyday spending and missing payment dates.')}</Text>}
    <Text style={s.title}>{t('2 · Zahlungen prüfen','2 · Review payments')}</Text>{button(t('Zahlungen ansehen und abhaken','View and check off payments'),onPayments)}<Pressable accessibilityRole="checkbox" accessibilityState={{checked:q.reviewed}} style={s.disclosure} onPress={()=>q.setReviewed(!q.reviewed)}><Text style={s.note}>{q.reviewed?'✓':'○'} {t('Offene und bezahlte Zahlungen geprüft','Reviewed unpaid and paid payments')}</Text></Pressable><Text style={s.note}>{t('Offene Rechnungen bleiben offen. Du musst nicht alles als bezahlt markieren. Nach einer Änderung bitte erneut prüfen.','Unpaid bills stay unpaid. You do not need to mark everything paid. Review again after a change.')}</Text>
    <Text style={s.title}>{t('3 · Dein nächster sinnvoller Schritt','3 · Your next useful step')}</Text>{q.missingDate?button(`${q.missingDate.name} · ${t('Termin ergänzen','Add date')}`,()=>onReview?.(q.missingDate!)):q.opportunity?<><Text style={s.note}>{q.opportunity.name} · {t('Preis und Vertrag prüfen, ohne einen Wechsel vorzunehmen.','Review price and contract without making a switch.')}</Text>{button(t('Sparmöglichkeit ansehen','Review savings opportunity'),()=>onSavings?.())}</>:<Text style={s.note}>{t('Aktuell keine weitere Vertragsprüfung vorgeschlagen. Deine offenen Zahlungen bleiben im Plan.','No further contract review suggested right now. Your unpaid payments stay in the plan.')}</Text>}
    <Pressable accessibilityRole="button" disabled={!q.current||!q.reviewed||q.busy} accessibilityState={{disabled:!q.current||!q.reviewed||q.busy}} style={[s.button,(!q.current||!q.reviewed||q.busy)&&s.disabled]} onPress={()=>void q.finish()}><Text style={s.buttonText}>{t('Check abschließen','Complete check')}</Text></Pressable>{q.complete&&<Text style={s.good}>{t('Heute geprüft. Geänderte Angaben öffnen den Check erneut.','Reviewed today. Changed entries reopen the check.')}</Text>}{!!q.error&&<Text accessibilityRole="alert" style={s.error}>{q.error}</Text>}
  </>}</View>;
}
const s=StyleSheet.create({card:{padding:14,gap:12,backgroundColor:'#fff',borderTopWidth:1,borderTopColor:'#dfe5dd'},disclosure:{minHeight:44,flexDirection:'row',alignItems:'center',justifyContent:'space-between',gap:10},title:{fontSize:14,fontWeight:'700',color:'#24272c',flexShrink:1},note:{fontSize:13,lineHeight:20,color:'#52605b'},button:{alignSelf:'flex-start',minHeight:44,borderWidth:1,borderColor:'#dfe5dd',borderRadius:20,paddingHorizontal:12,paddingVertical:8,justifyContent:'center'},buttonText:{fontSize:13,fontWeight:'700',color:'#28734d'},disabled:{opacity:.45},good:{fontSize:13,fontWeight:'700',color:'#28734d'},error:{fontSize:13,color:'#b91c1c'}});
