import {test,expect} from '@playwright/test';
import {execFileSync} from 'node:child_process';
let script:string;
test.beforeAll(()=>{script=JSON.parse(execFileSync('node',['scripts/mobile-interaction-render.mjs'],{encoding:'utf8',maxBuffer:5_000_000})).script;});
async function show(page:import('@playwright/test').Page,view:string,locale:string){await page.setViewportSize({width:390,height:852});await page.setContent(`<!doctype html><html lang="${locale}"><style>*{box-sizing:border-box}body{font-family:Arial;margin:0;background:#f7f8f4}button,input{font:inherit;background:none;border:0;text-align:left}#root{padding:20px}output{display:none}</style><body data-view="${view}"><div id="root"></div><script>${script}</script></body></html>`);}
for(const locale of ['de','en']){
 test(`native field flow and picker ${locale}`,async({page},info)=>{
  await show(page,'cost',locale);const name=page.getByRole('textbox',{name:'Name',exact:true}),amount=page.getByRole('textbox',{name:locale==='de'?'Betrag':'Amount',exact:true});
  await expect(name).toHaveAttribute('placeholder',locale==='de'?'z. B. Internet':'e.g. Internet');await name.focus();await expect(name).not.toHaveAttribute('placeholder');await expect(name).toHaveAttribute('data-keyboard','default');await name.fill('Internet');await name.press('Enter');await expect(amount).toBeFocused();await expect(amount).toHaveAttribute('data-keyboard','decimal-pad');await expect(page.getByLabel('Saved count')).toHaveText('0');await amount.fill('40');
  await page.getByRole('button',{name:/Wie oft|How often/}).click();await page.getByRole('button',{name:locale==='de'?'Jährlich':'Yearly',exact:true}).click();await expect(page.getByRole('button',{name:/Wie oft|How often/})).toContainText(locale==='de'?'Jährlich':'Yearly');await amount.focus();await amount.press('Enter');await expect(page.getByLabel('Saved count')).toHaveText('1');await page.screenshot({fullPage:true,path:info.outputPath(`native-cost-flow-${locale}.png`)});
 });
 test(`native plan links focus the balance and navigate to payments ${locale}`,async({page},info)=>{
  await show(page,'payday',locale);await page.getByRole('button',{name:locale==='de'?'Finanzplan prüfen':'Review your money plan',exact:true}).click();await page.getByRole('button',{name:locale==='de'?'Kontostand und Alltag prüfen':'Review balance and everyday spending',exact:true}).click();const balance=page.getByRole('textbox',{name:locale==='de'?'Aktueller Kontostand':'Current account balance',exact:true});await expect(balance).toBeFocused();await expect(page.getByLabel('Navigation target')).toHaveText('balance');await balance.fill('1000');await balance.press('Enter');await expect(page.getByRole('textbox',{name:/Nächstes Gehalt|Next payday/})).toBeFocused();await page.getByRole('button',{name:locale==='de'?'Zahlungen ansehen und abhaken':'View and check off payments',exact:true}).click();await expect(page.getByLabel('Navigation target')).toHaveText('month');await page.screenshot({fullPage:true,path:info.outputPath(`native-payday-flow-${locale}.png`)});
 });
 test(`native annual comparison advances between numeric fields ${locale}`,async({page})=>{
  await show(page,'tools',locale);await page.getByRole('button',{name:locale==='de'?'Monatsabo oder Jahresabo?':'Monthly or annual subscription?',exact:true}).click();await page.getByRole('button',{name:/^Internet ·/}).click();const amount=page.getByRole('textbox',{name:locale==='de'?'Angebot: voller Jahrespreis':'Offer: full annual price',exact:true}),date=page.getByRole('textbox',{name:/Jahreszahlung am|Annual payment on/});await amount.fill('180');await amount.press('Enter');await expect(date).toBeFocused();await date.press('Enter');await expect(date).not.toBeFocused();await expect(page.getByLabel('Saved count')).toHaveText('0');
 });
 test(`native note saves a dated reminder without creating a payment ${locale}`,async({page},info)=>{
  await show(page,'notes',locale);await page.getByRole('textbox',{name:locale==='de'?'Notiz':'Note',exact:true}).fill(locale==='de'?'Internetvertrag prüfen':'Review internet contract');await page.getByRole('textbox',{name:locale==='de'?'Notiz':'Note',exact:true}).press('Enter');await expect(page.getByRole('textbox',{name:locale==='de'?'Erinnern am (optional)':'Reminder date (optional)',exact:true})).toBeFocused();await page.getByRole('textbox',{name:locale==='de'?'Erinnern am (optional)':'Reminder date (optional)',exact:true}).fill('31122026');await page.getByRole('button',{name:locale==='de'?'Notiz speichern':'Save note',exact:true}).click();await expect(page.getByLabel('Saved count')).toHaveText('1');await page.getByRole('button',{name:/Später|Later/}).click();await expect(page.getByRole('checkbox')).toHaveCount(1);await expect(page.getByRole('checkbox')).toContainText(locale==='de'?'Internetvertrag prüfen':'Review internet contract');await page.screenshot({fullPage:true,path:info.outputPath(`native-notes-flow-${locale}.png`)});
 });
}
