import {test,expect} from '@playwright/test';
for(const de of [false,true])for(const width of [390,1365])test(`Pro checkmarks, one change and hidden details ${de?'de':'en'} ${width}`,async({page},info)=>{
 await page.setViewportSize({width,height:900});await page.clock.setFixedTime(new Date('2026-10-05T12:00:00Z'));await page.emulateMedia({reducedMotion:'reduce'});
 await page.goto(de?'/de/zuhause':'/home');await page.getByRole('button',{name:de?'Zuhause erstellen':'Create my home',exact:true}).click();
 await page.evaluate(()=>{const p=JSON.parse(localStorage.getItem('eavesence-home-profile-v1')!);p.incomeAmount=2400;p.overviewReviewed=true;p.backupReminderDismissed=true;p.planning={cash:{balance:1400,asOf:'2026-10-05',payday:'2026-10-25',protected:100,everydayRemaining:200}};localStorage.setItem('eavesence-home-profile-v1',JSON.stringify(p));const base={frequency:'monthly',updatedAt:'2026-10-05T08:00:00Z'};localStorage.setItem('eavesence-home-costs-v1',JSON.stringify([{...base,id:'rent',name:'Rent',category:'housing',amount:900,nextDueDate:'2026-10-01'},{...base,id:'stream',name:'Streaming',category:'subscriptions',amount:18,nextDueDate:'2026-10-05'},{...base,id:'internet',name:'Internet',category:'subscriptions',amount:40,nextDueDate:'2026-10-05'}]));});await page.reload();
 const workspace=page.getByRole('navigation',{name:/Choose workspace|Bereich wählen/});await workspace.getByRole('button',{name:/Plan & save|Planen & sparen/}).click();const payday=page.getByRole('region',{name:/Your available budget|Dein verfügbarer Spielraum/});
 await payday.getByRole('button',{name:/Check off payments until payday|Zahlungen bis zum Gehalt abhaken/}).click();const rent=payday.getByRole('checkbox',{name:/^Rent ·/});await rent.check();await expect(rent).toBeChecked();await expect(payday).toContainText(de?'Bitte aktualisiere deinen Kontostand':'Please update your account balance');
 await payday.getByRole('button',{name:de?'Kontostand aktualisieren':'Update account balance',exact:true}).click();await payday.getByLabel(de?'Aktueller Kontostand':'Current account balance',{exact:true}).fill('500');await payday.getByRole('button',{name:de?'Spielraum berechnen':'Calculate available money',exact:true}).click();await expect(payday).toContainText(de?'142,00':'142.00');await payday.getByRole('button',{name:de?'Einklappen':'Collapse',exact:true}).click();await payday.screenshot({path:info.outputPath(`pro-payments-${de?'de':'en'}-${width}.png`)});expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);
 await workspace.getByRole('button',{name:de?'Übersicht':'Overview',exact:true}).click();const monthly=page.getByRole('region',{name:/Monthly checklist|Monatscheckliste/});await monthly.getByRole('button',{name:de?'Zahlungen abhaken':'Check off payments',exact:true}).click();await expect(monthly.getByRole('checkbox',{name:/^Rent ·/})).toBeChecked();
 await workspace.getByRole('button',{name:/Plan & save|Planen & sparen/}).click();const questions=page.getByRole('group',{name:/Choose planning question|Planungsfrage wählen/});await questions.getByRole('button',{name:/Find realistic savings|Realistisch sparen/}).click();const coach=page.getByRole('region',{name:/02 ·/});
 await expect(coach.getByRole('button',{name:de?'Änderung planen':'Plan change',exact:true})).toHaveCount(1);await expect(page.getByLabel(de?'Alltagsausgaben pro Monat (geschätzt)':'Everyday spending per month (estimate)',{exact:true})).toBeHidden();
 await coach.getByLabel(de?'Kostenänderung testen · Kosten auswählen':'Test a cost change · choose a cost').selectOption('stream');await expect(coach.getByRole('button',{name:de?'Änderung planen':'Plan change',exact:true})).toHaveCount(0);await coach.getByLabel(de?'Neuer Betrag je Zahlung (0 = fällt weg)':'New amount per payment (0 = ends)').fill('0');await coach.screenshot({path:info.outputPath(`pro-one-change-${de?'de':'en'}-${width}.png`)});expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);await coach.getByRole('button',{name:de?'Änderung vormerken':'Save this plan',exact:true}).click();
 await coach.getByText(de?/Vorgemerkte Änderungen/:/Planned changes/).click();page.once('dialog',d=>void d.accept());await coach.getByRole('button',{name:de?'Umgesetzt – Kosten aktualisieren':'Done — update costs'}).click();await questions.getByRole('button',{name:/Savings achieved|Erreichte Ersparnis/}).click();const progress=page.getByRole('region',{name:/03 ·/});await expect(progress).toContainText(de?'18,00':'18.00');const details=progress.locator('details');await expect(details).not.toHaveAttribute('open','');await expect(progress.getByText('Streaming',{exact:true})).toBeHidden();await details.locator('summary').click();await expect(progress.getByText('Streaming',{exact:true})).toBeVisible();await details.locator('summary').click();await progress.scrollIntoViewIfNeeded();await page.screenshot({path:info.outputPath(`pro-simple-${de?'de':'en'}-${width}.png`)});expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);
});
test('failed Pro checkmark keeps the bill open and the saved balance intact',async({page})=>{
 await page.clock.setFixedTime(new Date('2026-10-05T12:00:00Z'));await page.goto('/home');await page.getByRole('button',{name:'Create my home',exact:true}).click();await page.evaluate(()=>{const p=JSON.parse(localStorage.getItem('eavesence-home-profile-v1')!);p.overviewReviewed=true;p.planning={cash:{balance:1400,asOf:'2026-10-05',payday:'2026-10-25',protected:0,everydayRemaining:0}};localStorage.setItem('eavesence-home-profile-v1',JSON.stringify(p));localStorage.setItem('eavesence-home-costs-v1',JSON.stringify([{id:'rent',name:'Rent',category:'housing',amount:900,frequency:'monthly',nextDueDate:'2026-10-01',updatedAt:'2026-10-01T00:00:00Z'}]));});await page.reload();await page.getByRole('navigation',{name:'Choose workspace'}).getByRole('button',{name:/Plan & save/}).click();const payday=page.getByRole('region',{name:'Your available budget'});await payday.getByRole('button',{name:/Check off payments until payday/}).click();await page.evaluate(()=>{const original=Storage.prototype.setItem;Storage.prototype.setItem=function(key,value){if(key==='eavesence-home-profile-v1')throw new DOMException('Storage full','QuotaExceededError');return original.call(this,key,value);};});const rent=payday.getByRole('checkbox',{name:/^Rent ·/});await rent.click();await expect(payday.getByRole('alert')).toContainText('Could not save this checkmark');await expect(rent).not.toBeChecked();expect(await page.evaluate(()=>JSON.parse(localStorage.getItem('eavesence-home-profile-v1')!).planning.cash.needsRefresh)).toBeUndefined();
});
