"use client";
import type { ReactNode } from "react";
import { usePlanning } from '@eavesence/core/usePlanning';
import type { PlanningData } from '@eavesence/core/planning';
import type { SavingsPlanInput } from '@eavesence/core/savingsPlan';

type Props={costChange?:ReactNode;input:SavingsPlanInput;data?:PlanningData;onSave:(data:PlanningData)=>void|Promise<void>;locale:'de'|'en';currency:string;onEditCosts:()=>void;onEditIncome:()=>void;onEditBudget:()=>void};
const field='home-planning-field min-h-11 min-w-0 w-full rounded-xl border border-[#cddbd0] bg-white px-3 text-[16px] text-[#17211f]';
const button='eavesence-pill-button home-dashboard-action';
export default function PlanningWorkbench({input,data,onSave,locale,currency,onEditCosts,onEditIncome,onEditBudget,costChange}:Props) {
 const de=locale==='de';const p=usePlanning(input,data,onSave,de);
 const money=(n:number)=>new Intl.NumberFormat(de?'de-AT':'en-GB',{style:'currency',currency}).format(n);
 const month=(s:string)=>new Intl.DateTimeFormat(de?'de-AT':'en-GB',{month:'long',year:'numeric',timeZone:'UTC'}).format(new Date(`${s}-01T00:00:00Z`));
 return <section className="mt-5 space-y-3" aria-label={de?'Vorausschauend planen':'Plan ahead'}>
  <div className="min-w-0 rounded-xl border border-[#cddbd0] bg-white p-4">
   <h3 className="site-card-title">{de?'Dein Monatscheck':'Your monthly check'}</h3>
   <p className="mt-1 text-[12px] text-[#52605b]">{de?'Prüfe nur, was sich geändert hat. Deine bisherigen Angaben bleiben erhalten.':'Review only what changed. Your existing entries stay in place.'}</p>
   {!p.canCheck?<p className="mt-3 text-[12px]">{de?'Ergänze zuerst Einkommen, mindestens eine Fixkostenausgabe und deine Alltagsschätzung.':'First add income, at least one fixed cost and your everyday-spending estimate.'}</p>:p.reviewed?<p role="status" className="mt-3 text-[13px] font-semibold text-[#087a45]">{de?'Für diesen Monat geprüft. Änderungen an deinem Budget öffnen den Check erneut.':'Reviewed this month. Budget changes reopen the check.'}</p>:<>
    <div className="mt-3 space-y-2">{[de?`Einkommen passt: ${money(input.incomeMonthly)}`:`Income is current: ${money(input.incomeMonthly)}`,de?`Fixkosten geprüft: ${money(p.plan?.averageFixed??0)} im Monatsdurchschnitt`:`Fixed costs reviewed: ${money(p.plan?.averageFixed??0)} monthly average`,de?`Alltagsschätzung passt: ${money(input.variableMonthly??0)}`:`Everyday estimate is current: ${money(input.variableMonthly??0)}`].map((label,i)=><label key={i} className="flex items-center gap-2 text-[13px]"><input type="checkbox" checked={p.checks[i]} onChange={e=>p.setChecks(p.checks.map((v,n)=>n===i?e.target.checked:v))}/>{label}</label>)}</div>
    <button type="button" className={`${button} mt-3`} disabled={p.busy||!p.checks.every(Boolean)} onClick={()=>void p.finishCheck()}>{de?'Monatscheck abschließen':'Complete monthly check'}</button>
   </>}
   <div className="mt-3 flex flex-wrap gap-3"><button type="button" className={button} onClick={onEditIncome}>{de?"Einkommen ändern":"Update income"}</button><button type="button" className={button} onClick={onEditCosts}>{de?'Kosten prüfen / ändern':'Review / update costs'}</button><button type="button" className={button} onClick={onEditBudget}>{de?'Alltagsschätzung ändern':'Update everyday estimate'}</button></div>
   {p.data.checks.length>0&&<details className="home-disclosure mt-3 text-[12px]"><summary>{de?'Bisherige Monatschecks':'Previous monthly checks'}</summary>{p.data.checks.map(c=><p key={c.month} className="mt-2">{month(c.month)} · {de?'Rest nach Fixkosten und Alltag':'Left after fixed costs and everyday spending'}: {money(c.incomeMonthly-c.fixedMonthly-c.variableMonthly)}</p>)}</details>}
  </div>
  <section aria-labelledby="planning-goals-title" className="pt-3">
   <h3 id="planning-goals-title" className="site-card-title text-[#17211f]">{de?'Ziele & Rücklagen':'Goals & reserves'}</h3>
   <div className="mt-3 grid items-start gap-3 lg:grid-cols-2">
  <details className="home-disclosure min-w-0 rounded-xl border border-[#cddbd0] bg-white p-4">
   <summary className="cursor-pointer site-card-title"><span>{de?'Sparziele mit Zweck und Datum':'Savings goals with a purpose and date'}</span><span className="mt-1 block text-[12px] font-normal leading-5 text-[#52605b]">{de?'Plane, wofür du Geld zurücklegen möchtest.':'Plan what you want to set money aside for.'}</span></summary>
   <p className="mt-2 text-[12px] text-[#52605b]">{de?'Trage nur Geld als zurückgelegt ein, das du tatsächlich für dieses Ziel reserviert hast. Die Ziele verteilen deinen Sparbetrag; sie werden nicht zusätzlich vom Budget abgezogen.':'Only enter money actually set aside for this goal. Goals allocate your savings amount; they are not deducted again.'}</p>
   {p.goals.map(g=><article key={g.id} className="mt-3 rounded-xl bg-[#eefbf3] p-3 text-[13px]"><strong>{g.name}</strong><p>{money(g.saved)} / {money(g.target)} · {month(g.targetMonth)}</p><progress aria-label={g.name} value={g.percent} max={100} className="mt-2 w-full accent-[#087a45]"/><p>{g.remaining===0?(de?'Ziel erreicht.':'Goal reached.'):g.overdue?(de?'Zieldatum vorbei. Datum anpassen.':'Target date passed. Update the date.'):`${de?'Noch nötig':'Still needed'}: ${money(g.monthly)} ${de?'pro Monat':'per month'}`}</p><div className="mt-2 flex gap-3"><button type="button" className={button} onClick={()=>p.editGoal(g)}>{de?'Guthaben / Ziel ändern':'Update balance / goal'}</button><button type="button" className={button} disabled={p.busy} onClick={()=>{if(window.confirm(de?'Dieses Sparziel entfernen? Dein tatsächliches Guthaben bleibt unverändert.':'Remove this goal? Your actual savings remain unchanged.'))void p.persist({...p.data,goals:p.data.goals.filter(x=>x.id!==g.id)});}}>{de?'Entfernen':'Remove'}</button></div></article>)}
   {p.goals.length>0&&<p className="mt-3 text-[12px]">{de?'Für alle Ziele nötig':'Needed for all goals'}: {money(p.required)} {de?'pro Monat. Eingetragener Sparbetrag':'per month. Your savings amount'}: {money(input.goalMonthly)}. {p.required>input.goalMonthly?(de?'Sparbetrag oder Zieldaten anpassen.':'Adjust the savings amount or target dates.'):(de?'Dein Sparbetrag deckt die benötigten Beiträge.':'Your savings amount covers the required contributions.')}</p>}
   <form onSubmit={e=>{e.preventDefault();void p.saveGoal();}} className="mt-4 grid gap-3 sm:grid-cols-2">
    <label className="grid gap-1 text-[12px]">{de?'Name des Sparziels':'Goal name'}<input className={field} value={p.name} onChange={e=>p.setName(e.target.value)} placeholder={de?'z. B. Urlaub':'e.g. Holiday'}/></label>
    <label className="grid gap-1 text-[12px]">{de?'Zielbetrag':'Target amount'}<input className={field} inputMode="decimal" value={p.target} onChange={e=>p.setTarget(e.target.value)}/></label>
    <label className="grid gap-1 text-[12px]">{de?'Für dieses Ziel bereits zurückgelegt':'Already set aside for this goal'}<input className={field} inputMode="decimal" value={p.saved} onChange={e=>p.setSaved(e.target.value)} placeholder="0"/></label>
    <label className="grid gap-1 text-[12px]">{de?'Zielmonat':'Target month'}<input className={field} type="month" value={p.targetMonth} onChange={e=>p.setTargetMonth(e.target.value)}/></label>
    <div className="flex gap-3"><button className={button} disabled={p.busy} type="submit">{p.editing?(de?'Ziel aktualisieren':'Update goal'):(de?'Sparziel speichern':'Save savings goal')}</button>{p.editing&&<button className={button} type="button" onClick={()=>p.editGoal()}>{de?'Abbrechen':'Cancel'}</button>}</div>
   </form>
  </details>
  <details className="home-disclosure min-w-0 rounded-xl border border-[#cddbd0] bg-white p-4">
   <summary className="cursor-pointer site-card-title"><span>{de?'Größere Rechnungen vorbereiten':'Prepare for larger bills'}</span><span className="mt-1 block text-[12px] font-normal leading-5 text-[#52605b]">{de?'Lege rechtzeitig Geld für fällige Rechnungen zurück.':'Set money aside before larger bills are due.'}</span></summary>
   <p className="mt-2 text-[12px] text-[#52605b]">{de?'Diese Rechnungen stehen bereits in deinen Fixkosten. Die Rücklagenplanung zieht sie nicht ein zweites Mal ab. Halte dieses Geld getrennt von deinen Sparzielen.':'These bills are already included in fixed costs. Reserve planning does not deduct them again. Keep this money separate from your savings goals.'}</p>
   {!p.reserves.length&&<p className="mt-3 text-[12px]">{de?'Erfasse eine jährliche, halbjährliche oder quartalsweise Rechnung.':'Add a yearly, half-yearly or quarterly bill.'}</p>}
   {p.reserves.map(r=><article key={r.cost.id} className="mt-3 rounded-xl bg-[#eefbf3] p-3 text-[13px]"><strong>{r.cost.name} · {money(r.cost.amount)}</strong><p>{r.dueMonth?`${de?'Fällig':'Due'}: ${month(r.dueMonth)} · ${de?'Bis dahin zurücklegen':'Set aside until then'}: ${money(r.monthly??0)} ${de?'pro Monat':'per month'}`:(de?'Zahlungstermin ergänzen, um den Rücklagenplan zu berechnen.':'Add a payment date to calculate the reserve plan.')}</p><label className="mt-2 grid gap-1 text-[12px]">{de?'Für diese Rechnung bereits zurückgelegt':'Already set aside for this bill'}<input className={field} inputMode="decimal" value={p.reserveDraft[r.cost.id]??String(r.saved)} onChange={e=>p.setReserveDraft({...p.reserveDraft,[r.cost.id]:e.target.value})}/></label><button type="button" disabled={p.busy} className={`${button} mt-2`} onClick={()=>void p.saveReserve(r.cost.id)}>{de?'Rücklage speichern':'Save set-aside amount'}</button></article>)}
  </details>
   </div>
  </section>
  <section aria-labelledby="planning-changes-title" className="pt-3">
   <h3 id="planning-changes-title" className="site-card-title text-[#17211f]">{de?'Änderungen ausprobieren':'Try changes'}</h3>
   <p className="mt-1 text-[12px] leading-5 text-[#52605b]">{de?'Beide Vorschauen nutzen deinen Sparplan oben. Du siehst, wie sich dein Spielraum verändert.':'Both previews use your savings plan above. See how your available budget would change.'}</p>
   <div className="mt-3 grid items-start gap-3 lg:grid-cols-2">
  <details className="home-disclosure min-w-0 rounded-xl border border-[#cddbd0] bg-white p-4">
   <summary className="cursor-pointer site-card-title"><span>{de?'Eine Anschaffung durchspielen':'Try a one-off purchase'}</span><span className="mt-1 block text-[12px] font-normal leading-5 text-[#52605b]">{de?'Was bleibt, wenn du einmalig Geld ausgibst?':'What is left after a one-off purchase?'}</span></summary>
   <p className="mt-2 text-[12px] text-[#52605b]">{de?'Die Vorschau verändert keine Kosten und führt keine Zahlung aus. Sie zeigt die Auswirkung auf deinen Monatsplan, nicht deinen Kontostand.':'This preview changes no costs and makes no payment. It shows the effect on your monthly plan, not your bank balance.'}</p>
   <div className="mt-3 grid gap-3 sm:grid-cols-2"><label className="grid gap-1 text-[12px]">{de?'Anschaffung':'Purchase'}<input className={field} value={p.purchaseName} onChange={e=>p.setPurchaseName(e.target.value)} placeholder={de?'z. B. Waschmaschine':'e.g. Washing machine'}/></label><label className="grid gap-1 text-[12px]">{de?'Einmaliger Betrag':'One-off amount'}<input className={field} inputMode="decimal" value={p.purchaseAmount} onChange={e=>p.setPurchaseAmount(e.target.value)}/></label><label className="grid gap-1 text-[12px]">{de?'Kaufmonat':'Purchase month'}<select className={field} value={p.purchaseMonth} onChange={e=>p.setPurchaseMonth(e.target.value)}>{p.plan?.months.map(m=><option key={m.month} value={m.month}>{month(m.month)}</option>)}</select></label><label className="grid gap-1 text-[12px]">{de?'Für den Kauf verfügbares Guthaben (optional)':'Funds available for this purchase (optional)'}<input className={field} inputMode="decimal" value={p.available} onChange={e=>p.setAvailable(e.target.value)}/><span>{de?'Nur frei verfügbares Geld, ohne bereits reservierte Beträge.':'Only unallocated money, excluding amounts already reserved.'}</span></label></div>
   {p.impact?<div role="status" className="mt-3 rounded-xl bg-[#eefbf3] p-3 text-[13px]"><strong>{p.purchaseName|| (de?'Deine Anschaffung':'Your purchase')}</strong><p>{de?'Rest nach Sparbetrag, vor Kauf':'Left after savings, before purchase'}: {money(p.impact.before)}</p><p>{de?'Nach dem Kauf im Monatsplan':'After purchase in the monthly plan'}: {money(p.impact.after)}</p>{p.impact.after<0&&<p>{de?'Für deinen unveränderten Plan fehlen':'Your unchanged plan falls short by'} {money(-p.impact.after)}. {p.impact.later?`${de?'Ein späterer Monat mit ausreichendem Plan-Spielraum':'A later month with enough planned room'}: ${month(p.impact.later)}.`:(de?'Kein passender Monat in dieser 12-Monats-Vorschau.':'No suitable month in this 12-month preview.')}</p>}{p.impact.goalShortfall>0&&<p>{de?"Wenn du den Kauf aus diesem Monatsbudget deckst, fehlen für deinen Sparbetrag":"If funded from this month’s budget, your savings contribution falls short by"}: {money(p.impact.goalShortfall)}. {input.goalMonthly>0&&`${de?"Bei gleicher Sparrate entspricht das rechnerisch bis zu":"At the same savings rate, that represents up to"} ${Math.ceil(p.impact.goalShortfall/input.goalMonthly)} ${de?"zusätzlichem Sparmonat.":"extra savings month."}`}</p>}{p.impact.availableAfter!==null&&<p>{de?'Von deinem angegebenen Guthaben bleiben':'Your entered available funds would become'}: {money(p.impact.availableAfter)}.</p>}<p className="mt-2 text-[12px]">{de?'Ein negatives Monatsergebnis kann aus vorhandenen Rücklagen gedeckt werden. Plane das bewusst; Guthaben und Monatsrest werden hier nicht zusammengerechnet.':'Existing savings may cover a negative monthly result. Plan this explicitly; available funds and monthly room are not added together here.'}</p></div>:<p className="mt-3 text-[12px]">{de?'Für die Vorschau brauchst du Einkommen, Alltagsschätzung und einen gültigen Kaufbetrag über 0.':'Add income, an everyday estimate and a valid positive purchase amount for the preview.'}</p>}
  </details>
    {costChange&&<details className="home-disclosure min-w-0 rounded-xl border border-[#cddbd0] bg-white p-4">
     <summary className="cursor-pointer site-card-title"><span>{de?'Eine Kostenänderung durchspielen':'Try a cost change'}</span><span className="mt-1 block text-[12px] font-normal leading-5 text-[#52605b]">{de?'Was bleibt, wenn eine laufende Ausgabe kleiner wird?':'What is left if a recurring cost goes down?'}</span></summary>
     {costChange}
    </details>}
   </div>
  </section>
  {p.error&&<p role="alert" className="text-[13px] text-red-700">{p.error}</p>}{p.notice&&<p role="status" className="text-[13px] font-semibold text-[#087a45]">{p.notice}</p>}
 </section>;
}
