"use client";
import { useProTools } from '@eavesence/core/useProTools';
import type { PlanningData } from '@eavesence/core/planning';
import type { SavingsPlanInput } from '@eavesence/core/savingsPlan';
const field='home-planning-field min-h-11 w-full min-w-0 rounded-xl border border-[#cddbd0] bg-white px-3';
const button='eavesence-pill-button home-dashboard-action';
export default function ProTools({input,data,onSave,onReview,currency,locale}:{input:SavingsPlanInput;data?:PlanningData;onSave:(p:PlanningData)=>void|Promise<void>;onReview:(c:SavingsPlanInput['costs'][number])=>void;currency:string;locale:'de'|'en'}) {
  const de=locale==='de',t=(a:string,b:string)=>de?a:b,p=useProTools(input,data,onSave,de);
  const money=(n:number)=>new Intl.NumberFormat(de?'de-AT':'en-GB',{style:'currency',currency}).format(n);
  const day=(s:string)=>new Intl.DateTimeFormat(de?'de-AT':'en-GB',{day:'numeric',month:'long',year:'numeric',timeZone:'UTC'}).format(new Date(`${s}T00:00:00Z`));
  return <section className="mt-4 grid items-start gap-3 lg:grid-cols-2" aria-label={t('Rechnungen und Abos planen','Plan bills and subscriptions')}>
    <details className="home-disclosure min-w-0 rounded-xl border border-[#dfe5dd] bg-white p-4">
      <summary className="site-card-title cursor-pointer">{t('Jahreskosten rechtzeitig vorbereiten','Prepare for annual bills')}</summary>
      <p className="mt-3 text-[13px] leading-5 text-[#52605b]">{t('Auch für Rechnungen alle drei oder sechs Monate. Der Monatsdurchschnitt ist eine Rechengröße; eine Rücklage ist Geld, das du wirklich dafür reserviert hast.','Also for quarterly and half-yearly bills. The monthly average is a calculation; a reserve is money you actually set aside.')}</p>
      {!p.reserves.length&&<p className="mt-3 text-[13px]">{t('Erfasse zuerst eine jährliche, halbjährliche oder quartalsweise Rechnung.','Add a yearly, half-yearly or quarterly bill first.')}</p>}
      {p.reserves.map(r=><article key={r.cost.id} className="mt-3 rounded-xl bg-[#f4f6f2] p-3 text-[13px]">
        <h4 className="font-bold">{r.cost.name}</h4>
        <p className="mt-1">{r.dueDate?`${r.overdue?t('Noch offen seit','Still unpaid since'):t('Fällig am','Due on')} ${day(r.dueDate)}: ${money(r.cost.amount)}`:t('Der Zahlungstermin fehlt.','Payment date missing.')}</p>
        <dl className="mt-3 space-y-1"><div className="flex justify-between gap-2"><dt>{t('Bereits zurückgelegt','Already set aside')}</dt><dd>{money(r.saved)}</dd></div><div className="flex justify-between gap-2"><dt>{t('Noch erforderlich','Still needed')}</dt><dd className="font-bold">{money(r.missing)}</dd></div></dl>
        {r.monthly!==null&&<p className="mt-2 font-semibold text-[#28734d]">{r.missing===0?t('Für diese Rechnung vollständig zurückgelegt.','Fully set aside for this bill.'):r.months===1?`${t('Diesen Monat noch zurücklegen','Still set aside this month')}: ${money(r.missing)}`:`${money(r.monthly)} ${t('pro Monat ab diesem Monat bis zur Fälligkeit','per month from this month until due')} (${r.months}).`}</p>}
        <p className="mt-2 text-[#52605b]">{t('Zum Vergleich: Monatsdurchschnitt','For comparison: monthly average')} {money(r.average)}. {t('Kein zusätzlicher Kostenabzug. Nach dem Abhaken gilt die Rücklage für den nächsten Termin wieder als 0.','No additional cost deduction. Once checked paid, the next payment starts with 0 set aside.')}</p>
        <form className="mt-3 grid gap-2" onSubmit={async e=>{e.preventDefault();await p.saveReserve(r.cost.id);}}><label className="grid gap-1">{t('Für diese Rechnung reserviertes Geld','Money reserved for this bill')}<input inputMode="decimal" className={field} value={p.reserveValue(r.cost.id)} onChange={e=>p.setReserveValue(r.cost.id,e.target.value)}/></label><div className="flex flex-wrap gap-2"><button className={button} disabled={p.busy} type="submit">{t('Rücklage speichern','Save reserve')}</button>{!r.dueDate&&<button className={button} type="button" onClick={()=>onReview(r.cost)}>{t('Termin ergänzen','Add date')}</button>}</div></form>
      </article>)}
    </details>
    <details className="home-disclosure min-w-0 rounded-xl border border-[#dfe5dd] bg-white p-4">
      <summary className="site-card-title cursor-pointer">{t('Monatsabo oder Jahresabo?','Monthly or annual subscription?')}</summary>
      <p className="mt-3 text-[13px] leading-5 text-[#52605b]">{t('Vergleiche ein echtes Angebot. Ein Jahresabo kann günstiger sein, braucht aber eine Vorauszahlung und bindet dich länger.','Compare an actual offer. An annual plan can cost less, but needs an upfront payment and a longer commitment.')}</p>
      {!p.subscriptions.length?<p className="mt-3 text-[13px]">{t('Erfasse zuerst ein monatliches Abo in der Kategorie „Verträge & Abos“.','Add a monthly cost in the Contracts & subscriptions category first.')}</p>:<div className="mt-3 grid gap-3">
        <label className="grid gap-1 text-[13px]">{t('Abo auswählen','Choose subscription')}<select className={field} value={p.costId} onChange={e=>p.setCostId(e.target.value)}><option value="">{t('Abo auswählen','Choose subscription')}</option>{p.subscriptions.map(c=><option key={c.id} value={c.id}>{c.name} · {money(c.amount)} {t('pro Monat','per month')}</option>)}</select></label>
        {p.selected&&<><label className="grid gap-1 text-[13px]">{t('Angebot: voller Jahrespreis','Offer: full annual price')}<input inputMode="decimal" className={field} value={p.annual} onChange={e=>p.setAnnual(e.target.value)}/></label><label className="grid gap-1 text-[13px]">{t('Jahreszahlung am','Annual payment on')}<input type="date" min={p.today} className={field} value={p.start} onChange={e=>p.setStart(e.target.value)}/></label>
        {p.comparison?<div className="rounded-xl bg-[#eefbf3] p-3 text-[13px]" role="status"><p className="font-bold">{p.comparison.annualSaving>0?`${t('Pro Jahr günstiger um','Costs less per year by')} ${money(p.comparison.annualSaving)}`:p.comparison.annualSaving<0?`${t('Pro Jahr teurer um','Costs more per year by')} ${money(-p.comparison.annualSaving)}`:t('Gleiche Kosten pro Jahr.','Same annual cost.')}</p><p className="mt-2">{t('Vorauszahlung','Upfront payment')}: {money(p.comparison.upfront)}. {t('Entspricht im Durchschnitt','Equivalent monthly average')}: {money(p.comparison.monthlyEquivalent)} {t('pro Monat','per month')}.</p><p className="mt-2">{p.comparison.after===null?t('Aktualisiere „Bis zum Gehalt“ für die Auswirkung auf deinen Spielraum.','Update To payday to see the effect on available money.'):p.comparison.inWindow?`${t('Nach der Umstellung bis zum Gehalt verfügbar','Available until payday after switching')}: ${money(p.comparison.after)}. ${t('Ersetzte offene Monatszahlungen','Replaced unpaid monthly charges')}: ${money(p.comparison.removed)}.`:t('Die Jahreszahlung liegt nach dem nächsten Gehalt. Dein aktueller Spielraum bleibt unverändert; plane die Vorauszahlung für später ein.','The annual payment is after your next payday. Current available money stays unchanged; prepare for the future upfront payment.')}</p>{p.comparison.after!==null&&p.comparison.after<0&&<p className="mt-2 font-semibold text-amber-900">{t('Für diesen Zeitpunkt reicht dein geplanter Spielraum nicht.','Your planned available money is insufficient at this time.')}</p>}<p className="mt-2">{t('Die Vorschau ersetzt Monatszahlungen ab dem gewählten Datum. Prüfe Nutzung, Bindung, automatische Verlängerung und Kündigungsfrist. Nur eine Vorschau: Es wird kein Vertrag geändert und keine Ersparnis verbucht.','The preview replaces monthly charges from the selected date. Check usage, commitment, automatic renewal and cancellation terms. Preview only: no contract changes or savings are recorded.')}</p></div>:<p className="text-[13px]">{t('Jahrespreis über 0 und ein Datum ab heute eingeben.','Enter a positive annual price and a date from today onwards.')}</p>}
        {p.comparison&&<><label className="grid gap-1 text-[13px]">{t('Entscheidung merken für','Remember decision on')}<input className={field} type="date" value={p.remindAt} onChange={e=>p.setRemindAt(e.target.value)}/></label><div className="flex flex-wrap gap-2"><button className={button} type="button" disabled={p.busy} onClick={()=>void p.rememberComparison(money)}>{t('Vergleich in My Home merken','Save comparison to My Home')}</button><button className={button} type="button" onClick={()=>onReview(p.selected!)}>{t('Nach Umstellung Kosten bearbeiten','Edit costs after switching')}</button></div><p className="text-[13px] text-[#52605b]">{t('Als Notiz unter „Merken & erinnern“. Keine automatische Benachrichtigung.','As a note under Notes & reminders. No automatic notification.')}</p></>}
        </>}
      </div>}
    </details>
    {p.error&&<p role="alert" className="text-[13px] text-red-700 lg:col-span-2">{p.error}</p>}{p.notice&&<p role="status" className="text-[13px] text-[#28734d] lg:col-span-2">{p.notice}</p>}
  </section>;
}
