"use client";
import { useQuickCheck } from '@eavesence/core/useQuickCheck';
import type { PlanningData } from '@eavesence/core/planning';
import type { SavingsPlanInput } from '@eavesence/core/savingsPlan';
export default function QuickCheck({input,data,onSave,onBalance,onPayments,onSavings,onReview,locale}:{input:SavingsPlanInput;data?:PlanningData;onSave:(p:PlanningData)=>void|Promise<void>;onBalance:()=>void;onPayments:()=>void;onSavings?:()=>void;onReview?:(c:SavingsPlanInput['costs'][number])=>void;locale:'de'|'en'}) {
  const de=locale==='de',t=(a:string,b:string)=>de?a:b,q=useQuickCheck(input,data,onSave,de),button='eavesence-pill-button home-dashboard-action';
  return <div className="border-t border-[#dfe5dd] bg-white p-4 sm:p-5" aria-label={t('Kurzer regelmäßiger Check','Quick regular check')}>
    <button className="flex min-h-11 w-full items-center justify-between gap-3 text-left text-[13px] font-semibold" type="button" aria-expanded={q.open} onClick={()=>q.setOpen(!q.open)}><span>{t('Kurzer Check','Quick check')}{q.complete?` · ${t('heute erledigt','done today')}`:''}</span><span aria-hidden="true" className={`text-xl text-[#28734d] transition-transform duration-200 motion-reduce:transition-none ${q.open?'-rotate-45':''}`}>+</span></button>
    {q.open&&<div className="mt-3 space-y-4 text-[13px]">
      <p className="text-[#52605b]">{t('Prüfe nur, was sich geändert hat. Deine Eingaben bleiben erhalten. Wiederhole den Check nach einer Abbuchung oder vor einer größeren Ausgabe.','Review only what changed. Your entries stay in place. Repeat after a debit or before a larger purchase.')}</p>
      <div><p className="font-semibold">{t('1 · Kontostand und Zeitraum','1 · Balance and time period')}{q.current?' ✓':''}</p><button type="button" className={`${button} mt-2`} onClick={onBalance}>{t('Kontostand und Alltag prüfen','Review balance and everyday spending')}</button>{!q.current&&<p className="mt-2 text-[#52605b]">{t('Aktuellen Kontostand, Gehaltstag, Alltag und fehlende Zahlungstermine ergänzen.','Update balance, payday, everyday spending and missing payment dates.')}</p>}</div>
      <div><p className="font-semibold">{t('2 · Zahlungen prüfen','2 · Review payments')}</p><button type="button" className={`${button} mt-2`} onClick={onPayments}>{t('Zahlungen ansehen und abhaken','View and check off payments')}</button><label className="mt-2 flex min-h-11 items-center gap-2"><input type="checkbox" checked={q.reviewed} onChange={e=>q.setReviewed(e.target.checked)} className="h-5 w-5 accent-[#28734d]"/>{t('Offene und bezahlte Zahlungen geprüft','Reviewed unpaid and paid payments')}</label><p className="text-[#52605b]">{t('Offene Rechnungen bleiben offen. Du musst nicht alles als bezahlt markieren. Nach einer Änderung bitte erneut prüfen.','Unpaid bills stay unpaid. You do not need to mark everything paid. Review again after a change.')}</p></div>
      <div><p className="font-semibold">{t('3 · Dein nächster sinnvoller Schritt','3 · Your next useful step')}</p>{q.missingDate?<button className={`${button} mt-2`} type="button" onClick={()=>onReview?.(q.missingDate!)}>{q.missingDate.name} · {t('Termin ergänzen','Add date')}</button>:q.opportunity?<><p className="mt-2">{q.opportunity.name} · {t('Preis und Vertrag prüfen, ohne einen Wechsel vorzunehmen.','Review price and contract without making a switch.')}</p><button className={`${button} mt-2`} type="button" onClick={onSavings}>{t('Sparmöglichkeit ansehen','Review savings opportunity')}</button></>:<p className="mt-2">{t('Aktuell keine weitere Vertragsprüfung vorgeschlagen. Deine offenen Zahlungen bleiben im Plan.','No further contract review suggested right now. Your unpaid payments stay in the plan.')}</p>}</div>
      <button type="button" className={button} disabled={!q.current||!q.reviewed||q.busy} onClick={()=>void q.finish()}>{t('Check abschließen','Complete check')}</button>{q.complete&&<p role="status" className="font-semibold text-[#28734d]">{t('Heute geprüft. Geänderte Angaben öffnen den Check erneut.','Reviewed today. Changed entries reopen the check.')}</p>}{q.error&&<p role="alert" className="text-red-700">{q.error}</p>}
    </div>}
  </div>;
}
